// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import type { IconName } from "./IconName";

export const IconTags = [
  "activity",
  "alert",
  "approve",
  "arrow",
  "arrows",
  "attention",
  "award",
  "basic",
  "bottom",
  "box",
  "cancel",
  "connection",
  "contextual",
  "create",
  "cross",
  "crosshair",
  "danger",
  "delete",
  "diagonal",
  "dismiss",
  "done",
  "dot",
  "east",
  "enlarge",
  "exit",
  "expand",
  "fail",
  "failure",
  "favorite",
  "feedback",
  "find",
  "finish",
  "form",
  "fyi",
  "help",
  "information",
  "inspect",
  "launch",
  "level",
  "list",
  "magnifier",
  "mark",
  "minus",
  "new",
  "news",
  "north",
  "outside",
  "plus",
  "rate",
  "rating",
  "recurring",
  "remove",
  "ring",
  "schedule",
  "search",
  "share",
  "shrink",
  "side",
  "simple",
  "south",
  "success",
  "tick",
  "tip",
  "top",
  "valid",
  "view",
  "warning",
  "west",
  "zoom",
] as const;
export type IconTag = (typeof IconTags)[number];
export const IconTagMap: Record<IconName, Array<IconTag>> = {
  add: ["create", "cross", "crosshair", "expand", "new", "plus"],
  "arrow-down": ["bottom", "south"],
  "arrow-down-left": ["bottom", "diagonal", "south", "west"],
  "arrow-down-right": ["bottom", "diagonal", "east", "south"],
  "arrow-left": ["side", "west"],
  "arrow-right": ["east", "side"],
  "arrow-up": ["north", "top"],
  "arrow-up-left": ["diagonal", "north", "top", "west"],
  "arrow-up-right": ["diagonal", "east", "north", "top"],
  check: [
    "approve",
    "done",
    "finish",
    "form",
    "list",
    "mark",
    "success",
    "tick",
    "valid",
  ],
  "chevron-down": ["arrow", "bottom", "south"],
  "chevron-left": ["arrow", "west"],
  "chevron-right": ["arrow", "east"],
  "chevron-up": ["arrow", "north", "top"],
  close: ["cancel", "delete", "dismiss", "exit", "fail", "failure", "remove"],
  "info-circle": [
    "attention",
    "contextual",
    "fyi",
    "help",
    "information",
    "news",
    "tip",
  ],
  "magnifying-glass": [
    "enlarge",
    "find",
    "inspect",
    "magnifier",
    "search",
    "shrink",
    "view",
    "zoom",
  ],
  "open-external": ["launch", "new", "outside", "share"],
  "shape-circle": ["basic", "dot", "ring", "simple"],
  "shape-square": ["basic", "box", "simple"],
  "shape-triangle": ["alert", "basic", "danger", "simple", "warning"],
  star: ["award", "favorite", "level", "rate", "rating"],
  subtract: ["delete", "minus", "remove"],
  sync: [
    "activity",
    "arrows",
    "connection",
    "feedback",
    "recurring",
    "schedule",
  ],
};
