// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/**
 * Auto-generated icon-name constants: one per icon, for call sites that prefer
 * a named import over a bare string literal.
 * DO NOT EDIT MANUALLY: regenerated by the sync from NVIDIA's internal
 * monorepo (see CONTRIBUTING.md).
 *
 * @module iconTypes
 *
 * @example
 * ```tsx
 * import { ADD, CHEVRON_RIGHT } from "@nvidia/micro-gui-icons/iconTypes";
 * import { NvidiaMicroGuiIcon } from "@nvidia/react-micro-gui-icons";
 *
 * <NvidiaMicroGuiIcon iconName={ADD} />
 * <NvidiaMicroGuiIcon iconName={CHEVRON_RIGHT} />
 * ```
 *
 * A name that starts with a digit is not a valid identifier, so the generator
 * gives those constants an `ICON_` prefix. No name in the Micro set needs one.
 */

import type { IconName } from "./IconName";

/**
 * Tree-shakable icon constants.
 * Each icon is exported as an individual constant for optimal bundle size.
 *
 * Note: Icons starting with numbers are prefixed with "ICON_"
 * Examples:
 *   "3d-axis" → ICON_3D_AXIS
 *   "4-square" → ICON_4_SQUARE
 *   "2b-left-click" → ICON_2B_LEFT_CLICK
 */

// Individual icon exports (tree-shakable)
export const ADD = "add" satisfies IconName;
export const ARROW_DOWN = "arrow-down" satisfies IconName;
export const ARROW_DOWN_LEFT = "arrow-down-left" satisfies IconName;
export const ARROW_DOWN_RIGHT = "arrow-down-right" satisfies IconName;
export const ARROW_LEFT = "arrow-left" satisfies IconName;
export const ARROW_RIGHT = "arrow-right" satisfies IconName;
export const ARROW_UP = "arrow-up" satisfies IconName;
export const ARROW_UP_LEFT = "arrow-up-left" satisfies IconName;
export const ARROW_UP_RIGHT = "arrow-up-right" satisfies IconName;
export const CHECK = "check" satisfies IconName;
export const CHEVRON_DOWN = "chevron-down" satisfies IconName;
export const CHEVRON_LEFT = "chevron-left" satisfies IconName;
export const CHEVRON_RIGHT = "chevron-right" satisfies IconName;
export const CHEVRON_UP = "chevron-up" satisfies IconName;
export const CLOSE = "close" satisfies IconName;
export const INFO_CIRCLE = "info-circle" satisfies IconName;
export const MAGNIFYING_GLASS = "magnifying-glass" satisfies IconName;
export const OPEN_EXTERNAL = "open-external" satisfies IconName;
export const SHAPE_CIRCLE = "shape-circle" satisfies IconName;
export const SHAPE_SQUARE = "shape-square" satisfies IconName;
export const SHAPE_TRIANGLE = "shape-triangle" satisfies IconName;
export const STAR = "star" satisfies IconName;
export const SUBTRACT = "subtract" satisfies IconName;
export const SYNC = "sync" satisfies IconName;
