// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

/**
 * Auto-generated AI-friendly icon constants.
 * DO NOT EDIT MANUALLY - This file is generated by the icon download script.
 *
 * @module iconTypes
 *
 * @example
 * ```tsx
 * // Import individual icons (tree-shakable)
 * import { ADD, ARROW_DOWN, SAVE } from "@nvidia/[base-icon-package]/iconTypes";
 *
 * <IconComponent iconName={ADD} />
 * <IconComponent iconName={ARROW_DOWN} />
 *
 * // Icons starting with numbers have "ICON_" prefix
 * import { ICON_3D_AXIS, ICON_4_SQUARE } from "@nvidia/[base-icon-package]/iconTypes";
 * <IconComponent iconName={ICON_3D_AXIS} />  // Original: "3d-axis"
 * <IconComponent iconName={ICON_4_SQUARE} /> // Original: "4-square"
 *
 * // Import category namespaces
 * import * as NAVIGATION from "@nvidia/[base-icon-package]/iconTypes";
 * import * as ACTIONS from "@nvidia/[base-icon-package]/iconTypes";
 *
 * <IconComponent iconName={NAVIGATION.ARROW_UP} />
 * <IconComponent iconName={ACTIONS.SAVE} />
 * ```
 */

import type { IconName } from "./IconName";

/**
 * Tree-shakable icon constants.
 * Each icon is exported as an individual constant for optimal bundle size.
 *
 * Note: Icons starting with numbers are prefixed with "ICON_"
 * Examples:
 *   "3d-axis" → ICON_3D_AXIS
 *   "4-square" → ICON_4_SQUARE
 *   "2b-left-click" → ICON_2B_LEFT_CLICK
 */

// Individual icon exports (tree-shakable)
export const ADD = "add" satisfies IconName;
export const ARROW_DOWN = "arrow-down" satisfies IconName;
export const ARROW_DOWN_LEFT = "arrow-down-left" satisfies IconName;
export const ARROW_DOWN_RIGHT = "arrow-down-right" satisfies IconName;
export const ARROW_LEFT = "arrow-left" satisfies IconName;
export const ARROW_RIGHT = "arrow-right" satisfies IconName;
export const ARROW_UP = "arrow-up" satisfies IconName;
export const ARROW_UP_LEFT = "arrow-up-left" satisfies IconName;
export const ARROW_UP_RIGHT = "arrow-up-right" satisfies IconName;
export const CHECK = "check" satisfies IconName;
export const CHEVRON_DOWN = "chevron-down" satisfies IconName;
export const CHEVRON_LEFT = "chevron-left" satisfies IconName;
export const CHEVRON_RIGHT = "chevron-right" satisfies IconName;
export const CHEVRON_UP = "chevron-up" satisfies IconName;
export const CLOSE = "close" satisfies IconName;
export const INFO_CIRCLE = "info-circle" satisfies IconName;
export const MAGNIFYING_GLASS = "magnifying-glass" satisfies IconName;
export const OPEN_EXTERNAL = "open-external" satisfies IconName;
export const SHAPE_CIRCLE = "shape-circle" satisfies IconName;
export const SHAPE_SQUARE = "shape-square" satisfies IconName;
export const SHAPE_TRIANGLE = "shape-triangle" satisfies IconName;
export const STAR = "star" satisfies IconName;
export const SUBTRACT = "subtract" satisfies IconName;
export const SYNC = "sync" satisfies IconName;
