// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

import type { IconName } from "./IconName";

export const IconCategories = [
  "3d",
  "av",
  "common",
  "communication",
  "cursor",
  "editor",
  "files",
  "hardware",
  "image",
  "maps",
  "misc",
  "shapes",
  "social",
  "view",
] as const;
export type IconCategory = (typeof IconCategories)[number];
export const IconCategoryMap: Record<IconCategory, Array<IconName>> = {
  "3d": [
    "3d-axis",
    "cloth",
    "cube",
    "dolly",
    "emissive",
    "explode",
    "instance",
    "light-rect",
    "light-rotate",
    "material",
    "move-global",
    "reference",
    "rotate-3d",
    "rotate-global",
    "segment",
    "shader",
    "shader-ball",
    "skeleton",
    "teapot",
    "teleport",
    "texture",
  ],
  av: [
    "auto-record",
    "auto-record-off",
    "broadcast",
    "camera",
    "camera-add",
    "camera-off",
    "clap-board",
    "closed-caption",
    "display-surround",
    "eject",
    "equalizer",
    "faders",
    "fast-forward",
    "fast-reverse",
    "file-reel",
    "film",
    "film-add",
    "film-collection",
    "forward-10",
    "fps",
    "high-quality",
    "hud",
    "loop",
    "loop-off",
    "microphone",
    "microphone-off",
    "next",
    "notes",
    "pause",
    "picture-in-picture",
    "play",
    "previous",
    "record",
    "replay",
    "replay-off",
    "reverse-10",
    "shuffle",
    "soundwaves",
    "speaker",
    "speaker-high",
    "speaker-low",
    "speaker-medium",
    "speaker-mute",
    "speaker-off",
    "step-forward",
    "step-reverse",
    "stop",
    "videocam",
    "videocam-off",
    "watch-party",
  ],
  common: [
    "add",
    "add-circle",
    "alarm",
    "bell",
    "bell-off",
    "calendar",
    "calendar-event",
    "cancel",
    "check",
    "check-circle",
    "check-multi-circle",
    "clipboard",
    "clock",
    "close",
    "close-circle",
    "cog",
    "cog-off",
    "copy-doc",
    "copy-generic",
    "enter",
    "error",
    "exit",
    "eye",
    "eye-off",
    "filter",
    "help-circle",
    "history",
    "home",
    "home-off",
    "inbox",
    "info-circle",
    "link",
    "link-break",
    "lock-closed",
    "lock-open",
    "magnifying-glass",
    "magnifying-glass-minus",
    "magnifying-glass-plus",
    "menu",
    "more-horiz",
    "more-vert",
    "outbox",
    "paperplane",
    "redo",
    "refresh",
    "reset",
    "retry",
    "share",
    "sort",
    "star",
    "subtract",
    "subtract-circle",
    "sync",
    "sync-off",
    "timer",
    "trash",
    "undo",
    "warning",
  ],
  communication: [
    "cloud",
    "cloud-off",
    "data",
    "download",
    "envelope",
    "envelope-off",
    "firewall",
    "firewall-off",
    "forward",
    "isp",
    "isp-off",
    "network-signal",
    "network-signal-off",
    "reply",
    "sync-warning",
    "transfer-horizontal",
    "transfer-vertical",
    "upload",
    "wifi",
    "wifi-off",
  ],
  cursor: [
    "arrow",
    "crosshair",
    "hand-closed",
    "hand-open",
    "hand-pinch",
    "hand-point",
    "hourglass",
    "hourglass-end",
    "hourglass-mid",
    "hourglass-start",
  ],
  editor: [
    "anchor",
    "anchor-center",
    "anchor-e",
    "anchor-n",
    "anchor-ne",
    "anchor-nw",
    "anchor-s",
    "anchor-se",
    "anchor-sw",
    "anchor-w",
    "approximately",
    "arrange-columns",
    "arrange-rows",
    "at-symbol",
    "backspace",
    "bold",
    "bounding-box",
    "chart",
    "chart-bar",
    "chart-bubble",
    "chart-flow",
    "chart-hierarchy",
    "chart-performance",
    "chart-pie",
    "chart-scatterplot",
    "chart-tree",
    "collapse",
    "commit",
    "connection",
    "craft-knife",
    "divide",
    "equal",
    "expand",
    "export-from-clipboard",
    "export-to-clipboard",
    "fit",
    "freehand",
    "generate",
    "grid",
    "grid-off",
    "h-align-center",
    "h-align-left",
    "h-align-right",
    "header",
    "highlighter",
    "image",
    "italic",
    "iterate",
    "keyframe",
    "lasso",
    "layers",
    "layers-off",
    "line-segment",
    "list-bullet",
    "list-checkmark",
    "list-number",
    "markdown",
    "move",
    "not-equal",
    "numbers",
    "paperclip",
    "paragraph",
    "pen",
    "pencil",
    "rename",
    "rotate",
    "rotate-90-clockwise",
    "rotate-90-counter",
    "ruler",
    "scale-down",
    "scale-reset",
    "scale-up",
    "scissors",
    "scm-branch",
    "scm-compare",
    "scm-fork",
    "scm-merge",
    "scm-pull",
    "scm-pull-close",
    "scm-pull-draft",
    "section",
    "section-bottom",
    "section-top",
    "select-brush",
    "signature",
    "skip",
    "sliders",
    "sort-ascending",
    "sort-descending",
    "sticker",
    "sticker-image",
    "sticker-shape",
    "sticker-text",
    "sticker-zoom",
    "strikethrough",
    "stroke-width",
    "style",
    "swatches",
    "text",
    "text-align-center",
    "text-align-full",
    "text-align-left",
    "text-align-right",
    "text-framed",
    "trash-delete",
    "typography",
    "underline",
    "v-align-bottom",
    "v-align-center",
    "v-align-top",
    "wand",
    "wrench",
  ],
  files: [
    "archive",
    "db",
    "document",
    "document-checkmark",
    "document-new",
    "document-preview",
    "export",
    "floppy",
    "folder-closed",
    "folder-open",
    "import",
    "split-file",
  ],
  hardware: [
    "2b-left-click",
    "battery-0",
    "battery-0-off",
    "battery-100",
    "battery-25",
    "battery-50",
    "battery-75",
    "battery-boost",
    "battery-charging",
    "bluetooth",
    "bluetooth-off",
    "calculator",
    "coaxial",
    "component",
    "cpu",
    "display",
    "display-collection",
    "display-column",
    "display-off",
    "display-row",
    "displayport",
    "drive-cloud",
    "drive-cloud-off",
    "drive-network",
    "drive-network-off",
    "drive-removable",
    "drive-removable-off",
    "drive-usb",
    "drive-usb-off",
    "drone",
    "dvi",
    "ethernet",
    "ethernet-port",
    "fan",
    "fan-loud",
    "fan-quiet",
    "flight-stick",
    "gamepad",
    "gamepad-off",
    "gamepad-start",
    "gpu",
    "gpu-card",
    "gpu-card-multi",
    "gpu-card-off",
    "gpu-off",
    "gpu-sync",
    "hdmi",
    "headset",
    "joystick-classic",
    "keyboard",
    "laptop",
    "laser",
    "lightning",
    "mac",
    "mac-off",
    "media-optical",
    "mini-displayport",
    "mosaic",
    "mouse-2b",
    "mouse-2b-right-click",
    "mouse-3-b",
    "mouse-scrollwheel",
    "mouse-scrollwheel-active",
    "multidrive",
    "network",
    "network-connection",
    "network-pcs",
    "nvidia-shield",
    "nvidia-shield-stand",
    "outlet-a",
    "outlet-b",
    "outlet-c",
    "outlet-e",
    "outlet-g",
    "outlet-h",
    "outlet-i",
    "outlet-j",
    "outlet-k",
    "outlet-l",
    "performance-high",
    "performance-low",
    "performance-medium",
    "phone-laptop",
    "plug-receptacle",
    "plug-usb",
    "plugin",
    "power",
    "power-supply-unit",
    "ram",
    "remote",
    "robot",
    "robot-arm",
    "robot-delivery",
    "robot-torso",
    "robot-wheels",
    "sd-card",
    "smartphone",
    "smartphone-off",
    "tablet",
    "tablet-off",
    "telephone",
    "telephone-off",
    "television",
    "television-retro",
    "usb",
    "vga",
    "vr",
    "watch",
    "webcam",
    "webcam-off",
    "webcam-settings",
    "whispermode",
    "wireless-modem",
    "wireless-modem-off",
    "workstation",
    "workstation-off",
    "workstation-system",
    "workstation-system-off",
  ],
  image: [
    "brush",
    "bucket",
    "camera-360",
    "camera-linked",
    "camera-super",
    "collection",
    "crop",
    "denoise",
    "easel",
    "eraser",
    "eyedropper",
    "group",
    "import-image",
    "mask-inside",
    "mask-outside",
    "mirror-horizontal",
    "mirror-vertical",
    "outpainting",
    "palette",
    "scale",
    "scale-relative",
    "scale-relative-off",
    "select-ellipse",
    "select-polygon",
    "select-rectangle",
    "send-image",
    "shapes",
    "sun-high",
    "sun-low",
    "sun-off-high",
    "transparency",
  ],
  maps: [
    "airplane",
    "airport",
    "bank",
    "bed",
    "bicycle",
    "briefcase",
    "bush",
    "business",
    "castle",
    "city",
    "datacenter",
    "dirt",
    "elevator",
    "emergency",
    "escalator",
    "factory",
    "farm",
    "flag",
    "flower",
    "fog",
    "fuel-can",
    "fuel-pump",
    "government",
    "grass",
    "gravel",
    "helicopter",
    "hill",
    "location",
    "location-off",
    "map",
    "map-off",
    "mountain",
    "mud",
    "park",
    "physical-exit",
    "river",
    "rock",
    "route",
    "sailboat",
    "sand",
    "sea",
    "ship",
    "signpost",
    "sky",
    "snow",
    "stair",
    "stone",
    "straw",
    "suitcase",
    "toolbox",
    "tree",
    "trees",
    "water",
    "world",
    "world-off",
  ],
  misc: [
    "accessibility",
    "atom",
    "bandaid",
    "barcode",
    "beaker",
    "blackboard",
    "bone",
    "book",
    "bottle",
    "braille",
    "bug",
    "bug-off",
    "bus",
    "car",
    "cards",
    "checkmark-badge",
    "circle-1-q",
    "circle-2-q",
    "circle-3-q",
    "circle-tick",
    "code",
    "compass",
    "concierge",
    "crown",
    "cube-stack",
    "delivery-truck",
    "die-1",
    "die-2",
    "die-3",
    "die-4",
    "die-5",
    "die-6",
    "ekg",
    "engine",
    "facial-recognition",
    "fingerprint",
    "fire",
    "firecracker",
    "firework",
    "food",
    "footprint",
    "fork",
    "function",
    "gift",
    "graduate",
    "graph-node",
    "graph-node-connect",
    "graph-node-delete",
    "head",
    "health",
    "high-kick",
    "hit",
    "hot-air-balloon",
    "hydrant",
    "ime",
    "infinity",
    "key",
    "knife",
    "lamp",
    "library",
    "library-games",
    "lifebuoy",
    "lightbulb",
    "lighthouse",
    "magnet",
    "man",
    "man-woman",
    "mapping",
    "martini",
    "math",
    "meal",
    "medicine",
    "megaphone",
    "microscope",
    "mode-component",
    "money",
    "money-coin",
    "money-paper",
    "moon",
    "moon-off",
    "mug",
    "mug-beer",
    "neural-network",
    "news",
    "os",
    "package",
    "pawn",
    "pawprint",
    "payment-card",
    "pizza",
    "placesetting",
    "platformer",
    "podium",
    "prayer-room",
    "projector",
    "pulse",
    "puzzle",
    "qrcode",
    "radar",
    "radioactive",
    "rocket",
    "running",
    "saw-wave",
    "scale-balance",
    "school",
    "secure",
    "seed",
    "sensor",
    "shield",
    "shield-off",
    "ship-wheel",
    "shopping-bag",
    "shopping-basket",
    "shopping-cart",
    "shopping-cart-open",
    "sin-wave",
    "skull",
    "soccer",
    "sparkle",
    "split",
    "spoon",
    "square-wave",
    "steering-wheel",
    "suit-club",
    "suit-diamond",
    "suit-spade",
    "sword",
    "tag",
    "tag-label",
    "telescope",
    "thermometer",
    "ticket",
    "traffic-cone",
    "transform",
    "triangle-wave",
    "trident",
    "umbrella",
    "weather-cloud",
    "weather-fog",
    "weather-lightning",
    "weather-partial-cloud-day",
    "weather-partial-cloud-night",
    "weather-rain",
    "weather-snow",
    "weather-wind",
    "weight",
    "weight-bar",
    "wheel",
    "wheelchair",
    "wine-glass",
    "woman",
    "yoke",
  ],
  shapes: [
    "arrow-down",
    "arrow-down-left",
    "arrow-down-max",
    "arrow-down-right",
    "arrow-left",
    "arrow-left-max",
    "arrow-left-right",
    "arrow-right",
    "arrow-right-max",
    "arrow-up",
    "arrow-up-down",
    "arrow-up-left",
    "arrow-up-max",
    "arrow-up-right",
    "chevron-double-down",
    "chevron-double-left",
    "chevron-double-right",
    "chevron-double-up",
    "chevron-down",
    "chevron-down-left-up-right",
    "chevron-left",
    "chevron-left-right",
    "chevron-right",
    "chevron-up",
    "chevron-up-down",
    "chevron-up-left-down-right",
    "diamond",
    "diamond-off",
    "return",
    "shape-circle",
    "shape-circle-off",
    "shape-hexagon",
    "shape-octagon",
    "shape-square",
    "shape-square-off",
    "shape-triangle",
  ],
  social: [
    "account-add",
    "account-check",
    "account-more",
    "account-remove",
    "address-book",
    "award-ribbon",
    "award-trophy",
    "baby",
    "bookmark",
    "bookmark-off",
    "chat-message",
    "chat-multi",
    "chat-new",
    "chat-single",
    "chatbot",
    "family",
    "feeling-happy",
    "feeling-neutral",
    "feeling-sad",
    "feeling-very-happy",
    "feeling-very-sad",
    "founders",
    "founders-tier-1",
    "founders-tier-2",
    "founders-tier-3",
    "heart",
    "heart-off",
    "identification",
    "license",
    "pin",
    "pin-off",
    "profile",
    "profile-group",
    "profile-off",
    "ranking-xp",
    "service-account",
    "thumb-down",
    "thumb-up",
  ],
  view: [
    "3-square-plus",
    "4-square",
    "apps",
    "carousel-horizontal",
    "carousel-vertical",
    "display-share",
    "dual",
    "feedback",
    "fit-to-page",
    "fullscreen",
    "fullscreen-exit",
    "gallery-strip",
    "grip-area",
    "grip-corner",
    "grip-edge-horizontal",
    "grip-edge-vertical",
    "grip-mini",
    "layout-columns",
    "layout-detail",
    "layout-grid",
    "layout-list",
    "layout-rows",
    "open-external",
    "pill-bar-stack",
    "rectangle-group",
    "render",
    "segmap",
    "stack-horizontal",
    "window",
    "window-code",
    "window-grid",
    "window-stack",
    "window-terminal",
    "workspace",
    "workspace-group",
  ],
};

export const IconTags = [
  "503",
  "6",
  "8",
  "Forecast",
  "IT",
  "LED",
  "SKU",
  "URL",
  "a11y",
  "access",
  "accessibility",
  "accomModation",
  "account",
  "accounts",
  "achievement",
  "acorn",
  "action",
  "actions",
  "activity",
  "ada",
  "add",
  "addition",
  "additional",
  "address",
  "adjust",
  "administration",
  "advance",
  "affect",
  "aft",
  "after",
  "again",
  "against",
  "age",
  "agriculture",
  "ai",
  "aid",
  "aim",
  "air",
  "aircraft",
  "alarm",
  "alcohol",
  "ale",
  "alert",
  "algorithm",
  "alike",
  "all",
  "all ages",
  "all up",
  "ally",
  "alternative",
  "amount",
  "amplify",
  "amplitude",
  "analysis",
  "anatomy",
  "android",
  "angle brackets",
  "animal",
  "animation",
  "annotation",
  "announce",
  "answer",
  "answers",
  "anti",
  "appearance",
  "apple",
  "application",
  "applications",
  "approve",
  "approved",
  "apps",
  "arcade",
  "archive",
  "area",
  "areas",
  "arrange",
  "array",
  "arrow",
  "arrows",
  "art",
  "artboard",
  "articles",
  "articulation",
  "artificial intelligence",
  "aspect ratio",
  "assured",
  "astronomy",
  "atc",
  "attach",
  "attached",
  "attachment",
  "attempt",
  "attention",
  "attraction",
  "audio",
  "authentication",
  "autograph",
  "automatic",
  "automation",
  "automobile",
  "automotive",
  "av",
  "avatar",
  "avatars",
  "aviation",
  "avoid",
  "award",
  "back",
  "background",
  "backup",
  "backward",
  "backwards",
  "bad",
  "badge",
  "bag",
  "baggage",
  "balanced",
  "ball",
  "ballpoint",
  "bang",
  "bar",
  "barbell",
  "barn",
  "barrier",
  "bars",
  "base",
  "basic",
  "beacon",
  "beam",
  "bee",
  "before",
  "begin",
  "beginning",
  "bell",
  "benchmark",
  "bernoulli",
  "beverage",
  "big",
  "bigger",
  "bike",
  "bill",
  "billboard",
  "bin",
  "binary",
  "binder",
  "biometric",
  "biometrics",
  "birds",
  "bit",
  "bits",
  "blast",
  "blizzard",
  "block",
  "blocked",
  "blocker",
  "blocks",
  "blustery",
  "boat",
  "body",
  "boil",
  "bolt",
  "bones",
  "books",
  "boot",
  "border",
  "bottom",
  "boulder",
  "boundary",
  "bounds",
  "bow",
  "box",
  "boxing",
  "brain",
  "branches",
  "break",
  "breakfast",
  "bridge",
  "bright",
  "broadcast",
  "broken",
  "browse",
  "browser",
  "bucketing",
  "build",
  "building",
  "buildings",
  "built-in",
  "bulb",
  "bulk",
  "bullhorn",
  "bundle",
  "burger",
  "burn",
  "burst",
  "business",
  "busy",
  "buttons",
  "buy",
  "buzzer",
  "cable",
  "cactus",
  "call",
  "camera",
  "can",
  "cancel",
  "canvas",
  "capacity",
  "capsule",
  "capture",
  "card",
  "cards",
  "care",
  "cargo",
  "carriage",
  "castle",
  "casual",
  "categories",
  "categorize",
  "caution",
  "cave",
  "cd",
  "celebration",
  "cells",
  "central processing unit",
  "certificate",
  "chain",
  "chalk",
  "change",
  "channel",
  "chapel",
  "character",
  "characters",
  "charged",
  "chat",
  "check",
  "checked",
  "checkin",
  "checkout",
  "chemistry",
  "chess",
  "child",
  "chip",
  "choose",
  "cinema",
  "circle",
  "circuit",
  "circular",
  "city",
  "clapper",
  "clarify",
  "classic",
  "classroom",
  "cli",
  "click",
  "climbing",
  "clip",
  "clips",
  "clock",
  "clone",
  "close",
  "clothes",
  "clothing",
  "cloud",
  "cloudy",
  "cluster",
  "clustering",
  "cocktail",
  "code",
  "coffee",
  "coin",
  "cold",
  "collaboration",
  "collapse",
  "colleagues",
  "collecting",
  "collection",
  "college",
  "color",
  "colorful",
  "coloring",
  "colors",
  "combined displays",
  "combo",
  "combustion",
  "command line interface",
  "commerce",
  "communication",
  "communications",
  "community",
  "compare",
  "complex",
  "component",
  "components",
  "compute",
  "computed",
  "computer",
  "computers",
  "computing",
  "config",
  "configuration",
  "confirm",
  "confirmed",
  "conform",
  "connect",
  "connected",
  "connection",
  "connections",
  "connector",
  "connectors",
  "console",
  "construction",
  "contacts",
  "container",
  "containers",
  "content",
  "contents",
  "contextual",
  "continuous",
  "contrast",
  "control",
  "controller",
  "controls",
  "conversation",
  "convert",
  "coordinate",
  "coordinates",
  "copy",
  "core",
  "corner",
  "corners",
  "count",
  "couple",
  "courier",
  "cover",
  "covered",
  "coworkers",
  "crash",
  "create",
  "credit",
  "crescent",
  "critical",
  "crops",
  "cross",
  "crosshair",
  "cruise",
  "crunch",
  "crystal",
  "cube",
  "cuisine",
  "cup",
  "currency",
  "cursor",
  "custom",
  "customize",
  "cut",
  "cutlery",
  "cycle",
  "cycles",
  "d-pad",
  "daisy chain",
  "danger",
  "dark",
  "dashboard",
  "data",
  "data center",
  "data entry",
  "data visualization",
  "data viz",
  "database",
  "date",
  "day",
  "dcs",
  "dead",
  "death",
  "debit",
  "deck",
  "decor",
  "dedicated",
  "deep",
  "delay",
  "delete",
  "demo",
  "demolition",
  "denominator",
  "department",
  "deposit",
  "description",
  "desert",
  "design",
  "desktop",
  "details",
  "detection",
  "developer",
  "development",
  "device",
  "dexterity",
  "diagonal",
  "diagram",
  "dialogue",
  "dice",
  "dictate",
  "diff",
  "different",
  "digits",
  "dim",
  "dimensions",
  "dining",
  "dinner",
  "direct",
  "direction",
  "directions",
  "directory",
  "dirt",
  "disable",
  "disabled",
  "disapprove",
  "disc",
  "discover",
  "discreet",
  "discs",
  "dish",
  "disk",
  "dislike",
  "dismiss",
  "disorder",
  "displace",
  "display",
  "distance",
  "distribute",
  "divide",
  "divided",
  "divisor",
  "dl",
  "dock",
  "doctor",
  "document",
  "documentation",
  "documents",
  "dog",
  "dollar",
  "done",
  "dosage",
  "dose",
  "dot",
  "dots",
  "double",
  "down",
  "down arrow",
  "downpour",
  "draft",
  "drag",
  "drape",
  "draw",
  "drawer",
  "drawing",
  "drink",
  "drive",
  "drivers",
  "driving",
  "drizzle",
  "drop",
  "dry",
  "dry erase",
  "dunes",
  "duplicate",
  "dvd",
  "dynamite",
  "earth",
  "east",
  "eclipse",
  "edge",
  "edges",
  "edit",
  "education",
  "eight",
  "electricity",
  "electromagnetism",
  "electronics",
  "elegant",
  "elevation",
  "ellipses",
  "ellipsis",
  "email",
  "embed",
  "emergency",
  "emit",
  "emotion",
  "emphasis",
  "empty",
  "emt",
  "enable",
  "encode",
  "end",
  "energy",
  "enlarge",
  "enter",
  "enterprise",
  "entertainment",
  "entry",
  "environment",
  "eq",
  "equation",
  "error",
  "escape",
  "estimation",
  "ethernet",
  "etiquette",
  "even",
  "evening",
  "event",
  "events",
  "example",
  "exchange",
  "exercise",
  "exit",
  "exiting",
  "expand",
  "expansion",
  "experience",
  "experiment",
  "expire",
  "explode",
  "explore",
  "extend",
  "exterior",
  "extra",
  "eye",
  "eyeball",
  "fabric",
  "face",
  "faces",
  "fail",
  "failure",
  "fan",
  "fantasy",
  "faq",
  "farm",
  "fast",
  "father",
  "favorite",
  "feature",
  "federal",
  "feedback",
  "female",
  "festival",
  "fight",
  "fighting",
  "figure",
  "file",
  "files",
  "fill",
  "filled",
  "final",
  "finance",
  "find",
  "fine dining",
  "finish",
  "finished",
  "first aid",
  "fishing",
  "fit",
  "fitness",
  "fix",
  "fixture",
  "flag",
  "flake",
  "flame",
  "flash",
  "flash. els",
  "flee",
  "flight",
  "float",
  "flood",
  "floors",
  "floppy",
  "flow",
  "flush",
  "fly",
  "flying",
  "fold",
  "folded",
  "font",
  "food",
  "foot",
  "force",
  "forecast",
  "forest",
  "fork",
  "form",
  "format",
  "fortress",
  "forward",
  "fossil",
  "four",
  "fraction",
  "frame",
  "frames",
  "frames per second",
  "frank",
  "freestyle",
  "freight",
  "frequencies",
  "frequency",
  "friends",
  "front desk",
  "full",
  "funnel",
  "fyi",
  "gadget",
  "gale",
  "game",
  "games",
  "gaming",
  "garbage",
  "garbage can",
  "gasoline",
  "gather",
  "gauge",
  "gear",
  "genai",
  "generic",
  "genre",
  "geography",
  "gesture",
  "get",
  "get out",
  "git",
  "give",
  "glass",
  "global",
  "globe",
  "go",
  "goal",
  "goggles",
  "good",
  "grab",
  "graph",
  "graphic",
  "graphics",
  "graphics processing unit",
  "grassland",
  "gray",
  "green",
  "grid",
  "ground",
  "group",
  "grouping",
  "groups",
  "grove",
  "grow",
  "guard",
  "guidance",
  "guide",
  "guidelines",
  "gust",
  "half",
  "hamburger",
  "hand",
  "handicap",
  "handle",
  "handles",
  "hands",
  "handset",
  "hang",
  "hanger",
  "happened",
  "hard drives",
  "hardware",
  "harvest",
  "hat",
  "hazy",
  "hdd",
  "head",
  "headline",
  "headlines",
  "headphones",
  "headpiece",
  "heads up display",
  "health",
  "healthy",
  "hear",
  "heart",
  "heartbeat",
  "heat",
  "heavy",
  "help",
  "hertz",
  "hewn",
  "hexagonal",
  "hidden",
  "hide",
  "hierarchy",
  "high",
  "high point",
  "high power",
  "hike",
  "histogram",
  "history",
  "hold",
  "honeycomb",
  "honor",
  "hook",
  "horizon",
  "horizontal",
  "hospital",
  "hot",
  "hot chocolate",
  "hotel",
  "hotspot",
  "house",
  "hov",
  "hover",
  "hub",
  "hybrid",
  "hyperlink",
  "icy",
  "ide",
  "idea",
  "identical",
  "identification",
  "identifier",
  "identity",
  "ignore",
  "illumination",
  "imac",
  "image",
  "images",
  "imagine",
  "importance",
  "improve",
  "incident",
  "incoming",
  "increase",
  "index finger",
  "indicator",
  "individual",
  "industry",
  "infer",
  "information",
  "infrared",
  "infrastructure",
  "ink",
  "input",
  "insert",
  "inset",
  "inspect",
  "installer",
  "instance",
  "instant",
  "integrated development environment",
  "intensity",
  "interior",
  "internet",
  "inventory",
  "invisibility",
  "invisible",
  "ios",
  "ipad",
  "iphone",
  "iq",
  "ir",
  "irregular",
  "issue",
  "italian",
  "item",
  "items",
  "iterations",
  "jet",
  "jewels",
  "job",
  "joints",
  "journey",
  "juice",
  "jump",
  "jumping",
  "justified",
  "keep",
  "key",
  "keyhole",
  "keynote",
  "keys",
  "keystroke",
  "kid",
  "kindle",
  "king",
  "kingdom",
  "lab",
  "label",
  "lake",
  "lan",
  "landmark",
  "landmarks",
  "landscape",
  "language",
  "larger",
  "lattice",
  "launch",
  "launcher",
  "law",
  "lda",
  "leaf",
  "learn",
  "learning",
  "leave",
  "leaves",
  "lectern",
  "left",
  "legal",
  "legibility",
  "legislature",
  "lens",
  "letter",
  "letters",
  "level",
  "levels",
  "library",
  "lift",
  "light",
  "light show",
  "lighting",
  "like",
  "likeness",
  "limbs",
  "line",
  "lines",
  "link",
  "liquid",
  "list",
  "listing",
  "literacy",
  "live",
  "llm",
  "local",
  "local area",
  "local area network",
  "location",
  "lock",
  "locked",
  "login",
  "logistics",
  "look",
  "loop",
  "loud",
  "loudspeaker",
  "low",
  "low clouds",
  "low power",
  "low visibility",
  "lower",
  "lunch",
  "luxury",
  "machine",
  "macintosh",
  "magic",
  "magnetism",
  "magnifier",
  "magnify",
  "mail",
  "main",
  "maintain",
  "male",
  "malware",
  "manage",
  "management",
  "manual",
  "manufacture",
  "map",
  "maritime",
  "mark",
  "marker",
  "marquee",
  "martial arts",
  "mask",
  "mass",
  "mass transit",
  "massive",
  "match",
  "material",
  "materials",
  "math",
  "max",
  "maximize",
  "meal",
  "measure",
  "measurement",
  "measures",
  "mechanical",
  "media",
  "medical",
  "medication",
  "medicine",
  "medieval",
  "meditation",
  "medium",
  "meeting",
  "meetings",
  "melody",
  "memory",
  "men",
  "menu",
  "message",
  "method",
  "metropolis",
  "micro",
  "microphone",
  "middle",
  "mids",
  "migrate",
  "min",
  "mind",
  "mini",
  "minimize",
  "minus",
  "mist",
  "mix",
  "mixed",
  "mixology",
  "ml",
  "mobile",
  "modify",
  "modules",
  "monarch",
  "money",
  "monitor",
  "month",
  "moon",
  "more",
  "mosaic",
  "motel",
  "mother",
  "motherboard",
  "motion",
  "mount",
  "mouse",
  "move",
  "movement",
  "movie",
  "movies",
  "moving",
  "multimon",
  "multiple",
  "multiply",
  "music",
  "mute",
  "mystery",
  "mythology",
  "name",
  "natural",
  "nature",
  "nav",
  "navigate",
  "navigation",
  "negative",
  "network",
  "networking",
  "neutral",
  "neverending",
  "new",
  "new line",
  "news",
  "next",
  "night",
  "no alarm",
  "no camera",
  "no connection",
  "no controller",
  "no email",
  "no enlarge",
  "no eye",
  "no feature",
  "no gear",
  "no guidelines",
  "no network",
  "no networking",
  "no order",
  "no origin",
  "no picture",
  "no repeat",
  "no shape",
  "no simple",
  "no start",
  "no thumbtack",
  "no user",
  "no voice",
  "no weather",
  "node",
  "nodes",
  "noggin",
  "noise",
  "normal",
  "north",
  "northeast",
  "northwest",
  "not same",
  "notation",
  "note",
  "notebook",
  "notes",
  "notification",
  "nuclear",
  "nucleus",
  "numbers",
  "numerator",
  "numeric",
  "nurse",
  "object",
  "objects",
  "oblique",
  "occupation",
  "ocean",
  "ocean liner",
  "office",
  "official",
  "offroad",
  "ok",
  "old",
  "on top",
  "one",
  "onion",
  "online",
  "opacity",
  "open",
  "open water",
  "opinion",
  "optical",
  "optics",
  "options",
  "orbit",
  "order",
  "ordered",
  "organic",
  "origin",
  "original",
  "os",
  "outdoors",
  "outgoing",
  "output",
  "outside",
  "over",
  "overcast",
  "overlay",
  "package",
  "padlock",
  "page",
  "pages",
  "paint",
  "painting",
  "pair",
  "pan",
  "panels",
  "panorama",
  "panoramic",
  "paper",
  "parents",
  "parking",
  "part",
  "partial",
  "particles",
  "parts",
  "pass",
  "pass along",
  "passenger",
  "passes",
  "password",
  "past",
  "paste",
  "pasture",
  "patch",
  "patch cable",
  "path",
  "pathfinding",
  "pattern",
  "pause",
  "pc",
  "pci",
  "peak",
  "pebbles",
  "pedals",
  "pen",
  "pencil",
  "people",
  "perforations",
  "performance",
  "period",
  "periodical",
  "peripheral",
  "permanent",
  "person",
  "personal",
  "personalized",
  "pet",
  "petals",
  "petrol",
  "pharmacy",
  "photo",
  "photography",
  "photos",
  "pick",
  "picker",
  "pickup",
  "picnic",
  "picture",
  "pie",
  "piece",
  "pieces",
  "pile",
  "pilot",
  "pin",
  "ping",
  "pivot",
  "place",
  "planet",
  "planets",
  "plant",
  "plants",
  "plate",
  "play",
  "playback",
  "player",
  "playground",
  "playing",
  "playlist",
  "plug",
  "plugged in",
  "plus",
  "point",
  "pointer",
  "points",
  "poke",
  "policy",
  "polygon",
  "poof",
  "poor",
  "port",
  "portable",
  "portfolio",
  "portion",
  "ports",
  "poseidon",
  "position",
  "positive",
  "pound",
  "power",
  "precision",
  "preferences",
  "prescription",
  "present",
  "presentation",
  "press",
  "preview",
  "previous",
  "price",
  "primitive",
  "primitives",
  "print",
  "prior",
  "privacy",
  "private",
  "prize",
  "problem",
  "process",
  "processing",
  "processor",
  "product",
  "production",
  "prongs",
  "proof",
  "properties",
  "protected",
  "protection",
  "proxy",
  "pub",
  "public",
  "public address",
  "pull",
  "pulse",
  "punch",
  "purchase",
  "push",
  "put",
  "pyrotechnics",
  "quadrants",
  "queen",
  "query",
  "question",
  "quick redirect",
  "quiet",
  "race",
  "racing",
  "ragged",
  "raid",
  "rain",
  "rainy",
  "ramp",
  "random",
  "random access memory",
  "randomization",
  "range",
  "rank",
  "rate",
  "rating",
  "rays",
  "react",
  "read",
  "readability",
  "reading",
  "rearrange",
  "recall",
  "recant",
  "receive",
  "receiver",
  "receptacle",
  "reception",
  "receptor",
  "recipient",
  "record",
  "recording",
  "records",
  "recreation",
  "rectangular",
  "recurring",
  "recycle",
  "redact",
  "redeem",
  "reduce",
  "reel",
  "refine",
  "reflect",
  "reflection",
  "refresh",
  "refresh rate",
  "region",
  "regions",
  "reject",
  "religion",
  "relocate",
  "remember",
  "reminder",
  "remote",
  "remove",
  "render",
  "repair",
  "repeat",
  "repeats",
  "replay",
  "replenish",
  "replies",
  "reply",
  "resize",
  "resolution",
  "response",
  "rest",
  "restaurant",
  "restore",
  "restrooms",
  "result",
  "retail",
  "reticle",
  "retro",
  "return",
  "reverse",
  "revert",
  "reward",
  "rewind",
  "ride",
  "right",
  "ring",
  "rise",
  "river bank",
  "rock",
  "rocks",
  "rocky",
  "role playing",
  "roll",
  "rolling",
  "romance",
  "room",
  "rotate",
  "rotation",
  "rotors",
  "rough",
  "roughness",
  "round",
  "router",
  "row",
  "royal",
  "rpg",
  "rubbish",
  "rule",
  "running",
  "rural",
  "safe",
  "safety",
  "same",
  "sampler",
  "sash",
  "satisfaction",
  "save",
  "savings",
  "scale",
  "scan",
  "scene",
  "schedule",
  "school",
  "science",
  "scoop",
  "screen",
  "screen reader",
  "screens",
  "scribble",
  "scrub",
  "search",
  "sections",
  "secure",
  "security",
  "see",
  "see through",
  "segment",
  "segmentation",
  "segments",
  "select",
  "selection",
  "send",
  "send back",
  "sending",
  "sensor",
  "separate",
  "sequence",
  "served",
  "server",
  "servers",
  "session",
  "set",
  "set top box",
  "sets",
  "settings",
  "setup",
  "shade",
  "shadowplay",
  "share",
  "sheet",
  "shelf",
  "shield",
  "shift",
  "shiny",
  "ship",
  "shipment",
  "shoe",
  "shooter",
  "shop",
  "short",
  "shorthand",
  "show",
  "showcase",
  "shows",
  "shrink",
  "shrubbery",
  "shutdown",
  "shuttle",
  "side",
  "sides",
  "sideways",
  "sight",
  "sign",
  "signal",
  "signals",
  "signin",
  "silent",
  "silo",
  "similar",
  "simple",
  "simplify",
  "simulation",
  "simulator",
  "single",
  "singular",
  "six",
  "size",
  "skeleton",
  "skill",
  "skin",
  "skip",
  "skyline",
  "skyscraper",
  "skyscrapers",
  "slant",
  "slash",
  "slate",
  "sleep",
  "sli",
  "slice",
  "sliders",
  "slow",
  "small",
  "smaller",
  "smart",
  "smooth",
  "snapshot",
  "social",
  "socket",
  "software",
  "soil",
  "solo",
  "solution",
  "solve",
  "sonar",
  "sort",
  "sorting",
  "sound",
  "soundboard",
  "soup",
  "soupy",
  "source",
  "south",
  "southeast",
  "southwest",
  "space",
  "speaker",
  "speaking",
  "spear",
  "special",
  "speech bubble",
  "speech bubbles",
  "speed",
  "spin",
  "spinner",
  "split",
  "spokes",
  "sports",
  "spring",
  "sql",
  "square",
  "stack",
  "staff",
  "stage",
  "staircase",
  "stairs",
  "stairwell",
  "stalks",
  "stand",
  "standard",
  "star",
  "stars",
  "start",
  "start over",
  "state",
  "station",
  "stationary",
  "statistic",
  "statistics",
  "stay",
  "stb",
  "steam",
  "steer",
  "stein",
  "stems",
  "step",
  "steps",
  "sticky",
  "still",
  "stones",
  "stop",
  "stop repeating",
  "stop watch",
  "stopped",
  "storage",
  "store",
  "straight",
  "straightedge",
  "strategy",
  "streaming",
  "street",
  "stretch",
  "strike",
  "strip",
  "stripe",
  "strips",
  "stroke",
  "strokes",
  "strong",
  "structure",
  "students",
  "study",
  "style",
  "styles",
  "stylus",
  "sub",
  "subtitles",
  "subtract",
  "success",
  "suit",
  "summary",
  "sun",
  "sunset",
  "superimpose",
  "supply",
  "support",
  "surface",
  "surprise",
  "surround",
  "swipe",
  "switch",
  "swivel",
  "symbol",
  "sync",
  "synchronize",
  "syntax",
  "synthesizer",
  "tableware",
  "tabloid",
  "tactile",
  "tag",
  "tags",
  "tall",
  "tap",
  "target",
  "tasks",
  "tassel",
  "taxonomy",
  "tea",
  "teachers",
  "team",
  "television",
  "temperature",
  "template",
  "temporary",
  "tender",
  "terminal",
  "test",
  "text",
  "textures",
  "theater",
  "thickness",
  "think",
  "thought",
  "three",
  "threshold",
  "thumbnails",
  "thumbtack",
  "tick",
  "tie",
  "tile",
  "tiled",
  "time",
  "time series",
  "timing",
  "tip",
  "titanic",
  "title",
  "titles",
  "tix",
  "to",
  "to do",
  "together",
  "tool",
  "top",
  "toppings",
  "total",
  "touch",
  "tower",
  "toy",
  "trace",
  "track",
  "transfer",
  "translate",
  "translation",
  "translucency",
  "transmit",
  "transport",
  "transportation",
  "travel",
  "tread",
  "treble",
  "trend",
  "trial",
  "triangle",
  "trim",
  "trunk",
  "trusted",
  "try again",
  "turn",
  "tv",
  "tween",
  "twinkle",
  "twirl",
  "type",
  "types",
  "uav",
  "under",
  "undo",
  "unique",
  "unit identifier",
  "units",
  "universal",
  "university",
  "unlimited",
  "unlocked",
  "unmanned arial vehicle",
  "unmount",
  "unordered",
  "up",
  "up arrow",
  "update",
  "upper",
  "upper body",
  "urban",
  "url",
  "user",
  "users",
  "utensil",
  "utensils",
  "utilities",
  "utility",
  "vacation",
  "valence",
  "valid",
  "validate",
  "validated",
  "validation",
  "values",
  "vault",
  "vehicle",
  "vellum",
  "version",
  "vertical",
  "vessel",
  "vial",
  "video",
  "video chat",
  "video games",
  "videos",
  "view",
  "virtual",
  "virtual reality",
  "virus",
  "visibility",
  "visible",
  "vision",
  "visual",
  "visualization",
  "visuals",
  "voice",
  "volume",
  "volumes",
  "voyage",
  "vr",
  "waist up",
  "wait",
  "waiting",
  "wake",
  "walk",
  "wall",
  "wallet",
  "wan",
  "wap",
  "warm",
  "warning",
  "waste",
  "watch",
  "water",
  "wave",
  "waveform",
  "wavelength",
  "waves",
  "waypoint",
  "weapon",
  "wearable",
  "weather",
  "web",
  "week",
  "weights",
  "west",
  "wet",
  "wheel",
  "wheels",
  "whimsical",
  "whole",
  "whoosh",
  "wide area network",
  "widgets",
  "wifi",
  "wild",
  "wildlife",
  "win",
  "wind powered",
  "window",
  "wine",
  "wired",
  "wireless",
  "wiring",
  "withdrawal",
  "wizard",
  "women",
  "woods",
  "words",
  "work",
  "work out",
  "workflow",
  "working",
  "wormhole",
  "wrap around",
  "wrapped",
  "wrist",
  "write",
  "www",
  "wysiwyg",
  "year",
  "young",
  "zip",
  "zoom",
  "zoom in",
  "zoom out",
] as const;
export type IconTag = (typeof IconTags)[number];
export const IconTagMap: Record<IconName, Array<IconTag>> = {
  "2b-left-click": ["action", "buttons", "indicator"],
  "3-square-plus": [
    "add",
    "blocks",
    "four",
    "new",
    "quadrants",
    "sections",
    "split",
    "three",
  ],
  "3d-axis": ["dimensions", "directions", "guidelines", "rays"],
  "4-square": ["blocks", "four", "quadrants", "sections", "split"],
  accessibility: [
    "503",
    "a11y",
    "ally",
    "alternative",
    "contrast",
    "screen reader",
    "vision",
  ],
  "account-add": ["account", "add", "avatar", "new", "person", "photo", "user"],
  "account-check": [
    "account",
    "avatar",
    "confirm",
    "inspect",
    "person",
    "photo",
    "user",
    "validate",
  ],
  "account-more": [
    "account",
    "actions",
    "additional",
    "avatar",
    "details",
    "information",
    "person",
    "photo",
    "user",
  ],
  "account-remove": ["account", "avatar", "delete", "person", "photo", "user"],
  add: ["create", "cross", "crosshair", "expand", "new", "plus"],
  "add-circle": ["create", "cross", "crosshair", "expand", "new", "plus"],
  "address-book": [
    "binder",
    "contacts",
    "directory",
    "listing",
    "numbers",
    "people",
  ],
  airplane: ["air", "flight", "fly", "jet", "travel"],
  airport: [
    "atc",
    "aviation",
    "building",
    "flight",
    "location",
    "terminal",
    "tower",
    "transport",
    "travel",
  ],
  alarm: [
    "alert",
    "bell",
    "buzzer",
    "clock",
    "expire",
    "reminder",
    "ring",
    "signal",
    "time",
    "wake",
  ],
  anchor: [
    "URL",
    "attach",
    "boat",
    "core",
    "dock",
    "hyperlink",
    "navigate",
    "pivot",
    "ship",
  ],
  "anchor-center": ["lock", "middle", "origin", "point", "tie"],
  "anchor-e": ["lock", "origin", "point", "right", "tie"],
  "anchor-n": ["lock", "origin", "point", "tie", "top", "up"],
  "anchor-ne": ["lock", "origin", "point", "right", "tie", "top", "up"],
  "anchor-nw": ["left", "lock", "origin", "point", "tie", "top", "up"],
  "anchor-s": ["bottom", "lock", "origin", "point", "tie"],
  "anchor-se": ["bottom", "lock", "origin", "point", "right", "tie"],
  "anchor-sw": ["bottom", "left", "lock", "origin", "point", "tie"],
  "anchor-w": ["left", "lock", "origin", "point", "tie"],
  approximately: ["alike", "equation", "estimation", "math", "similar"],
  apps: ["applications", "dashboard", "launcher"],
  archive: ["box", "deep", "save", "shelf", "storage", "store"],
  "arrange-columns": ["move", "order", "rearrange", "sequence", "sort"],
  "arrange-rows": ["move", "order", "rearrange", "sequence", "sort"],
  arrow: ["click", "mouse", "pointer", "select"],
  "arrow-down": ["bottom", "south"],
  "arrow-down-left": ["bottom", "diagonal", "south", "west"],
  "arrow-down-max": ["bottom", "edge", "end", "south"],
  "arrow-down-right": ["bottom", "diagonal", "east", "south"],
  "arrow-left": ["side", "west"],
  "arrow-left-max": ["edge", "end", "side", "west"],
  "arrow-left-right": [
    "expand",
    "horizontal",
    "left",
    "right",
    "sides",
    "stretch",
  ],
  "arrow-right": ["east", "side"],
  "arrow-right-max": ["east", "edge", "end", "side"],
  "arrow-up": ["north", "top"],
  "arrow-up-down": ["down", "expand", "stretch", "up", "vertical"],
  "arrow-up-left": ["diagonal", "north", "top", "west"],
  "arrow-up-max": ["edge", "end", "north", "top"],
  "arrow-up-right": ["diagonal", "east", "north", "top"],
  "at-symbol": ["email", "receiver", "recipient", "target", "to"],
  atom: ["chemistry", "nuclear", "nucleus", "orbit", "valence"],
  "auto-record": [],
  "auto-record-off": ["movies", "no feature", "shadowplay", "videos"],
  "award-ribbon": [
    "achievement",
    "certificate",
    "honor",
    "official",
    "prize",
    "reward",
    "win",
  ],
  "award-trophy": ["achievement", "honor", "prize", "reward", "win"],
  baby: ["age", "care", "child", "father", "kid", "mother", "parents", "young"],
  backspace: ["character", "delete", "keystroke", "undo"],
  bandaid: ["fix", "health", "help", "medical", "patch"],
  bank: [
    "deposit",
    "finance",
    "location",
    "money",
    "office",
    "secure",
    "vault",
    "withdrawal",
  ],
  barcode: [
    "SKU",
    "automation",
    "buy",
    "identifier",
    "inventory",
    "item",
    "product",
    "retail",
    "scan",
    "shop",
    "track",
  ],
  "battery-0": ["empty", "level", "power"],
  "battery-0-off": ["empty", "level", "power"],
  "battery-100": ["charged", "full", "level", "power"],
  "battery-25": ["level", "low", "power"],
  "battery-50": ["half", "level", "medium", "power"],
  "battery-75": ["healthy", "level", "power"],
  "battery-boost": ["feature", "power", "savings"],
  "battery-charging": ["level", "plugged in", "power"],
  beaker: ["experiment", "glass", "lab", "liquid", "science", "trial", "vial"],
  bed: [
    "accomModation",
    "hotel",
    "location",
    "motel",
    "rest",
    "room",
    "sleep",
    "stay",
  ],
  bell: ["alarm", "alert", "notification", "reminder", "ring"],
  "bell-off": ["alert", "no alarm", "notification", "reminder", "ring"],
  bicycle: [
    "bike",
    "exercise",
    "fitness",
    "outdoors",
    "pedals",
    "ride",
    "vehicle",
    "wheels",
  ],
  blackboard: [
    "chalk",
    "classroom",
    "display",
    "dry erase",
    "education",
    "learning",
  ],
  bluetooth: ["format", "peripheral", "standard", "type", "wireless"],
  "bluetooth-off": ["format", "peripheral", "standard", "type", "wireless"],
  bold: ["document", "emphasis", "format", "heavy", "strong", "text"],
  bone: ["dog", "skeleton"],
  book: [
    "content",
    "education",
    "learn",
    "library",
    "manual",
    "pages",
    "read",
    "study",
    "text",
  ],
  bookmark: ["location", "mark", "note", "place", "position", "sash", "save"],
  "bookmark-off": [
    "location",
    "mark",
    "note",
    "place",
    "position",
    "sash",
    "save",
  ],
  bottle: ["alcohol", "bar", "container", "drink", "liquid", "vessel", "wine"],
  "bounding-box": [
    "annotation",
    "container",
    "coordinates",
    "detection",
    "handles",
    "image",
    "object",
    "selection",
  ],
  braille: ["accessibility", "communication", "literacy", "reading", "tactile"],
  briefcase: [
    "business",
    "documents",
    "job",
    "occupation",
    "portfolio",
    "work",
  ],
  broadcast: ["send", "signal", "tower", "waves"],
  brush: ["coloring", "drawing", "painting", "strokes"],
  bucket: ["art", "colors", "fill", "flood", "paint"],
  bug: ["code", "development", "error", "issue", "problem"],
  "bug-off": ["code", "development", "error", "issue", "problem"],
  bus: ["hov", "mass transit", "shuttle", "transportation"],
  bush: ["low", "plants", "shrubbery"],
  business: ["building", "city", "office", "skyscraper", "work"],
  calculator: ["classic", "crunch", "display", "numbers", "old"],
  calendar: [
    "date",
    "day",
    "event",
    "incident",
    "month",
    "picker",
    "schedule",
    "week",
    "year",
  ],
  "calendar-event": [
    "date",
    "day",
    "event",
    "incident",
    "month",
    "picker",
    "schedule",
    "special",
    "week",
    "year",
  ],
  camera: ["body", "image", "lens", "photography", "picture", "snapshot"],
  "camera-360": ["environment", "surround", "vr"],
  "camera-add": [
    "body",
    "image",
    "increase",
    "lens",
    "more",
    "new",
    "photography",
    "picture",
    "snapshot",
  ],
  "camera-linked": ["attached", "connected", "images", "photos", "wireless"],
  "camera-off": ["body", "disabled", "image", "lens", "no picture", "snapshot"],
  "camera-super": [],
  cancel: ["against", "anti", "delete", "remove"],
  car: ["automobile", "drive", "driving", "passenger", "travel", "vehicle"],
  cards: ["casual", "deck", "game", "genre"],
  "carousel-horizontal": ["billboard", "flow", "marquee", "order", "rotate"],
  "carousel-vertical": ["billboard", "flow", "marquee", "order", "rotate"],
  castle: [
    "building",
    "castle",
    "fortress",
    "history",
    "king",
    "kingdom",
    "landmark",
    "location",
    "medieval",
    "queen",
  ],
  chart: [
    "change",
    "data viz",
    "diagram",
    "graph",
    "time series",
    "visualization",
  ],
  "chart-bar": [
    "amount",
    "data viz",
    "diagram",
    "graph",
    "groups",
    "histogram",
    "vertical",
    "visualization",
  ],
  "chart-bubble": ["analysis", "data visualization", "graph", "statistics"],
  "chart-flow": [
    "connectors",
    "diagram",
    "direction",
    "graph",
    "lines",
    "nodes",
  ],
  "chart-hierarchy": [
    "diagram",
    "graph",
    "position",
    "rank",
    "structure",
    "taxonomy",
    "team",
  ],
  "chart-performance": [
    "change",
    "data viz",
    "direction",
    "goal",
    "movement",
    "trend",
    "visualization",
  ],
  "chart-pie": [
    "circle",
    "data viz",
    "diagram",
    "fraction",
    "graph",
    "segment",
    "visualization",
    "whole",
  ],
  "chart-scatterplot": ["data visualization", "points", "statistics"],
  "chart-tree": [
    "diagram",
    "graph",
    "leaf",
    "leaves",
    "structure",
    "taxonomy",
    "team",
    "trunk",
  ],
  "chat-message": ["content", "speech bubble"],
  "chat-multi": ["conversation", "dialogue", "speech bubbles"],
  "chat-new": ["add", "new", "speech bubble"],
  "chat-single": ["empty", "speech bubble"],
  chatbot: [
    "ai",
    "automation",
    "conversation",
    "llm",
    "replies",
    "reply",
    "smart",
    "virtual",
  ],
  check: [
    "approve",
    "done",
    "finish",
    "form",
    "list",
    "mark",
    "success",
    "tick",
    "valid",
  ],
  "check-circle": [
    "approve",
    "done",
    "finish",
    "form",
    "list",
    "mark",
    "success",
    "tick",
    "valid",
  ],
  "check-multi-circle": [
    "approve",
    "bulk",
    "done",
    "double",
    "finish",
    "form",
    "list",
    "mark",
    "success",
    "tick",
    "valid",
    "validated",
  ],
  "checkmark-badge": ["approved", "award", "special", "star", "validated"],
  "chevron-double-down": ["arrows", "bottom", "south"],
  "chevron-double-left": ["arrows", "side", "west"],
  "chevron-double-right": ["arrows", "east", "side"],
  "chevron-double-up": ["arrows", "north", "top"],
  "chevron-down": ["arrow", "bottom", "south"],
  "chevron-down-left-up-right": [
    "arrows",
    "corners",
    "diagonal",
    "northeast",
    "southwest",
  ],
  "chevron-left": ["arrow", "west"],
  "chevron-left-right": ["arrows", "east", "sides", "west"],
  "chevron-right": ["arrow", "east"],
  "chevron-up": ["arrow", "north", "top"],
  "chevron-up-down": ["arrows", "bottom", "north", "sides", "south", "top"],
  "chevron-up-left-down-right": [
    "arrows",
    "corners",
    "diagonal",
    "northwest",
    "southeast",
  ],
  "circle-1-q": [
    "animation",
    "delay",
    "hold",
    "pause",
    "spinner",
    "wait",
    "working",
  ],
  "circle-2-q": [
    "animation",
    "delay",
    "hold",
    "pause",
    "spinner",
    "wait",
    "working",
  ],
  "circle-3-q": [
    "animation",
    "delay",
    "hold",
    "pause",
    "spinner",
    "wait",
    "working",
  ],
  "circle-tick": ["burst", "delay", "ios", "spinner", "waiting"],
  city: [
    "buildings",
    "location",
    "metropolis",
    "skyline",
    "skyscrapers",
    "urban",
  ],
  "clap-board": [
    "begin",
    "clapper",
    "information",
    "movie",
    "recording",
    "scene",
    "tv",
  ],
  clipboard: ["copy", "edit", "paste", "store", "temporary"],
  clock: [
    "delay",
    "face",
    "hands",
    "period",
    "time",
    "timing",
    "wait",
    "watch",
  ],
  close: ["cancel", "delete", "dismiss", "exit", "fail", "failure", "remove"],
  "close-circle": [
    "cancel",
    "delete",
    "dismiss",
    "exit",
    "fail",
    "failure",
    "remove",
  ],
  "closed-caption": [
    "accessibility",
    "broadcast",
    "description",
    "media",
    "subtitles",
    "translation",
  ],
  cloth: ["clothing", "drape", "hang", "hanger", "materials", "type"],
  cloud: [
    "data center",
    "internet",
    "server",
    "wan",
    "weather",
    "wide area network",
  ],
  "cloud-off": [
    "data center",
    "internet",
    "no weather",
    "server",
    "wan",
    "wide area network",
  ],
  coaxial: ["cable", "connection", "display", "head", "port"],
  code: [
    "angle brackets",
    "cli",
    "close",
    "development",
    "open",
    "slash",
    "tags",
  ],
  cog: ["configuration", "gear", "preferences", "settings", "setup"],
  "cog-off": ["configuration", "no gear", "preferences", "settings", "setup"],
  collapse: ["hide", "minimize", "reduce", "smaller"],
  collection: [
    "collection",
    "drawing",
    "graphic",
    "group",
    "media",
    "painting",
    "photography",
    "picture",
    "print",
    "stack",
  ],
  commit: ["base", "code", "control", "git", "source", "version"],
  compass: [
    "directions",
    "hike",
    "location",
    "magnetism",
    "north",
    "pathfinding",
  ],
  component: ["cable", "connection", "display", "head", "port"],
  concierge: ["front desk", "help", "personalized", "staff"],
  connection: ["bridge", "line", "link", "nodes", "together"],
  "copy-doc": ["clone", "duplicate", "pages"],
  "copy-generic": ["clone", "duplicate"],
  cpu: ["central processing unit", "chip", "micro", "processor"],
  "craft-knife": ["cut", "graphics", "precision", "slice", "tool"],
  crop: ["area", "artboard", "aspect ratio", "clip", "trim"],
  crosshair: ["aim", "drop", "reticle", "shooter", "sight", "target"],
  crown: ["elegant", "headpiece", "jewels", "monarch", "power", "royal"],
  cube: ["bounds", "box", "container", "frame", "primitive", "square"],
  "cube-stack": ["building", "modules", "objects", "structure", "units"],
  data: [
    "binary",
    "bits",
    "information",
    "process",
    "receive",
    "send",
    "transmit",
  ],
  datacenter: [
    "IT",
    "building",
    "cloud",
    "computing",
    "enterprise",
    "infrastructure",
    "location",
    "processing",
    "scale",
    "servers",
    "storage",
  ],
  db: ["database", "records", "save", "sql", "storage"],
  "delivery-truck": ["cargo", "freight", "moving", "vehicle"],
  denoise: ["clarify", "refine", "simplify"],
  diamond: ["block", "instance", "mark", "simple"],
  "diamond-off": ["block", "instance", "mark", "no shape", "simple"],
  "die-1": ["count", "dice", "random", "roll"],
  "die-2": ["count", "dice", "random", "roll"],
  "die-3": ["count", "dice", "random", "roll"],
  "die-4": ["count", "dice", "random", "roll"],
  "die-5": ["count", "dice", "random", "roll"],
  "die-6": ["count", "dice", "random", "roll"],
  dirt: ["ground", "particles", "soil"],
  display: ["landscape", "monitor", "screen"],
  "display-collection": ["monitor", "mosaic", "multimon", "surround"],
  "display-column": ["bulk", "group", "multiple", "screens", "stack"],
  "display-off": ["landscape", "monitor", "screen"],
  "display-row": ["bulk", "group", "multiple", "screens"],
  "display-share": ["broadcast", "collaboration", "meeting", "screen", "send"],
  "display-surround": ["panorama", "panoramic", "screen", "wrap around"],
  displayport: ["cable", "connection", "display", "head", "port"],
  divide: [
    "denominator",
    "divisor",
    "equation",
    "fraction",
    "math",
    "numerator",
    "separate",
    "split",
  ],
  document: ["corner", "empty", "fold", "new", "page", "sheet"],
  "document-checkmark": [
    "confirmed",
    "corner",
    "done",
    "empty",
    "finished",
    "fold",
    "new",
    "page",
    "sheet",
    "validated",
  ],
  "document-new": ["corner", "empty", "fold", "new", "page", "plus", "sheet"],
  "document-preview": ["find", "look", "render", "search", "wysiwyg", "zoom"],
  dolly: ["aft", "backward", "forward", "move"],
  download: ["down arrow", "get", "pull", "save"],
  "drive-cloud": [
    "data center",
    "internet",
    "save",
    "server",
    "storage",
    "store",
  ],
  "drive-cloud-off": [
    "data center",
    "internet",
    "save",
    "server",
    "storage",
    "store",
  ],
  "drive-network": [
    "attached",
    "data center",
    "save",
    "server",
    "storage",
    "store",
  ],
  "drive-network-off": [
    "attached",
    "data center",
    "save",
    "server",
    "storage",
    "store",
  ],
  "drive-removable": [
    "bernoulli",
    "disk",
    "floppy",
    "media",
    "optical",
    "save",
    "storage",
    "store",
    "zip",
  ],
  "drive-removable-off": [
    "bernoulli",
    "disk",
    "floppy",
    "media",
    "optical",
    "save",
    "storage",
    "store",
    "zip",
  ],
  "drive-usb": ["data", "flash", "memory", "save", "storage", "store"],
  "drive-usb-off": ["data", "flash", "memory", "save", "storage", "store"],
  drone: ["flight", "personal", "remote", "uav", "unmanned arial vehicle"],
  dual: [
    "draft",
    "final",
    "hybrid",
    "image",
    "landscape",
    "rough",
    "segmentation",
  ],
  dvi: ["cable", "connection", "display", "head", "port"],
  easel: ["display", "present", "showcase", "stand"],
  eject: ["media", "remove", "unmount"],
  ekg: ["health", "heart", "monitor", "pulse"],
  elevator: ["floors", "lift", "mechanical"],
  emergency: ["emt", "first aid", "help", "medical"],
  emissive: ["emit", "send"],
  engine: [
    "automotive",
    "combustion",
    "machine",
    "mechanical",
    "performance",
    "power",
    "speed",
  ],
  enter: ["access", "go", "login", "signin"],
  envelope: ["email", "mail", "message", "send"],
  "envelope-off": ["mail", "message", "no email", "send"],
  equal: ["equation", "identical", "math", "result", "same", "solve"],
  equalizer: [
    "bars",
    "base",
    "eq",
    "frequencies",
    "frequency",
    "levels",
    "mids",
    "treble",
    "volume",
  ],
  eraser: ["delete", "remove", "scrub"],
  error: ["blocker", "crash", "critical", "failure", "issue", "terminal"],
  escalator: ["floors", "mechanical", "stairs"],
  ethernet: ["communications", "daisy chain", "hub", "lan", "network", "ports"],
  "ethernet-port": [
    "connector",
    "internet",
    "lan",
    "local area network",
    "patch cable",
    "port",
    "server",
  ],
  exit: ["close", "escape", "exit", "get out", "leave", "shutdown"],
  expand: ["bigger", "expand", "larger", "show"],
  explode: ["divide", "faces", "parts", "pieces", "separate"],
  export: ["convert", "process", "send", "share", "translate"],
  "export-from-clipboard": ["memory", "save", "send"],
  "export-to-clipboard": ["copy", "memory"],
  eye: ["enable", "eye", "eyeball", "open", "show", "visibility", "visible"],
  "eye-off": [
    "close",
    "disable",
    "eyeball",
    "hidden",
    "invisibility",
    "invisible",
    "no eye",
  ],
  eyedropper: ["color", "format", "picker", "sampler", "style"],
  "facial-recognition": [
    "authentication",
    "biometrics",
    "landmarks",
    "photo",
    "security",
    "video",
    "visual",
  ],
  factory: ["building", "industry", "manufacture", "production"],
  faders: ["levels", "mute", "settings", "sliders", "solo", "soundboard"],
  family: ["all ages", "casual", "game", "genre"],
  fan: ["flow", "hardware", "noise", "temperature"],
  "fan-loud": ["air", "high power", "noise", "speed", "volume"],
  "fan-quiet": ["air", "low power", "noise", "silent", "speed", "volume"],
  farm: [
    "agriculture",
    "barn",
    "buildings",
    "crops",
    "farm",
    "harvest",
    "location",
    "production",
    "rural",
    "silo",
  ],
  "fast-forward": ["control", "playback", "transport"],
  "fast-reverse": ["control", "playback", "rewind", "transport"],
  feedback: ["message", "speech bubble"],
  "feeling-happy": ["emotion", "good", "positive", "rating", "satisfaction"],
  "feeling-neutral": ["emotion", "neutral", "ok", "rating", "satisfaction"],
  "feeling-sad": [
    "bad",
    "emotion",
    "negative",
    "poor",
    "rating",
    "satisfaction",
  ],
  "feeling-very-happy": [
    "emotion",
    "good",
    "positive",
    "rating",
    "satisfaction",
  ],
  "feeling-very-sad": [
    "bad",
    "emotion",
    "negative",
    "poor",
    "rating",
    "satisfaction",
  ],
  "file-reel": ["cinema", "movie", "recording", "theater"],
  film: ["cells", "clip", "movie", "perforations", "reel", "strip", "video"],
  "film-add": ["animation", "media", "more", "movie", "plus"],
  "film-collection": [
    "cells",
    "clips",
    "group",
    "movies",
    "perforations",
    "reel",
    "stack",
    "strips",
    "videos",
  ],
  filter: ["funnel", "reduce", "refine"],
  fingerprint: ["authentication", "biometric", "identity", "security", "trace"],
  fire: ["burn", "combustion", "energy", "flame", "heat", "light"],
  firecracker: ["bang", "demolition", "dynamite", "explode", "loud"],
  firewall: ["block", "networking", "security"],
  "firewall-off": ["block", "no networking", "security"],
  firework: [
    "celebration",
    "event",
    "explode",
    "festival",
    "light show",
    "pyrotechnics",
  ],
  fit: ["conform", "enlarge", "expand", "fill", "reduce", "shrink"],
  "fit-to-page": ["find", "look", "render", "search", "wysiwyg", "zoom"],
  flag: ["landmark", "location", "remember", "save"],
  "flight-stick": [
    "aircraft",
    "control",
    "dcs",
    "flight",
    "gaming",
    "input",
    "navigation",
    "peripheral",
    "pilot",
    "simulator",
  ],
  floppy: ["data", "disk", "save", "storage", "store"],
  flower: ["colorful", "grow", "leaves", "petals", "spring", "stems", "wild"],
  fog: ["low clouds", "mist", "soupy", "visibility"],
  "folder-closed": ["container", "directory", "files", "path"],
  "folder-open": ["container", "directory", "files", "get", "path"],
  food: ["cuisine", "dining", "fast", "food", "meal", "restaurant"],
  footprint: ["path", "shoe", "step", "track", "walk"],
  fork: [
    "cutlery",
    "dining",
    "food",
    "meal",
    "poke",
    "spear",
    "tableware",
    "utensil",
  ],
  forward: ["next", "pass along", "send"],
  "forward-10": ["advance", "jump", "skip"],
  founders: ["badge", "importance", "level"],
  "founders-tier-1": ["badge", "importance", "level"],
  "founders-tier-2": ["badge", "importance", "level"],
  "founders-tier-3": ["badge", "importance", "level"],
  fps: ["frames per second", "hertz", "performance", "refresh rate", "speed"],
  freehand: ["draw", "form", "natural", "organic", "scribble"],
  "fuel-can": [
    "backup",
    "container",
    "gasoline",
    "offroad",
    "petrol",
    "storage",
  ],
  "fuel-pump": [
    "energy",
    "fossil",
    "gasoline",
    "petrol",
    "station",
    "transportation",
  ],
  fullscreen: [
    "all",
    "bigger",
    "cover",
    "display",
    "enlarge",
    "fill",
    "maximize",
    "total",
  ],
  "fullscreen-exit": ["inset", "reduce", "restore", "smaller", "window"],
  function: ["algorithm", "complex", "compute", "input", "output", "process"],
  "gallery-strip": ["browse", "images", "row", "thumbnails", "view"],
  gamepad: [
    "buttons",
    "console",
    "controller",
    "d-pad",
    "shield",
    "video games",
  ],
  "gamepad-off": [
    "buttons",
    "console",
    "controller",
    "d-pad",
    "shield",
    "video games",
  ],
  "gamepad-start": ["controller", "start"],
  generate: ["ai", "create", "genai", "imagine", "infer"],
  gift: ["bow", "package", "present", "reward", "sash", "wrapped"],
  government: [
    "administration",
    "buildings",
    "federal",
    "law",
    "legislature",
    "location",
    "policy",
    "state",
  ],
  gpu: ["chip", "graphics processing unit", "micro", "processor"],
  "gpu-card": ["dedicated", "discreet", "expansion", "motherboard", "pci"],
  "gpu-card-multi": [
    "dedicated",
    "discreet",
    "expansion",
    "group",
    "lda",
    "motherboard",
    "multiple",
    "pci",
    "sli",
  ],
  "gpu-card-off": ["dedicated", "discreet", "expansion", "motherboard", "pci"],
  "gpu-off": ["chip", "graphics processing unit", "micro", "processor"],
  "gpu-sync": ["coordinate", "match", "same", "synchronize", "timing"],
  graduate: [
    "college",
    "education",
    "hat",
    "learning",
    "school",
    "tassel",
    "university",
  ],
  "graph-node": ["activity", "input", "object", "output", "piece", "process"],
  "graph-node-connect": [
    "activity",
    "bridge",
    "input",
    "link",
    "object",
    "output",
    "piece",
    "process",
  ],
  "graph-node-delete": [
    "activity",
    "input",
    "object",
    "output",
    "piece",
    "process",
    "remove",
  ],
  grass: ["green", "low", "pasture", "short"],
  gravel: ["pebbles", "river bank", "rocks", "stones"],
  grid: ["blocks", "edges", "frames", "lattice", "no guidelines", "regions"],
  "grid-off": [
    "blocks",
    "edges",
    "frames",
    "lattice",
    "no guidelines",
    "regions",
  ],
  "grip-area": ["drag", "grab", "handle", "region", "tactile"],
  "grip-corner": ["corner", "drag", "grab", "handle", "tactile"],
  "grip-edge-horizontal": ["drag", "grab", "handle", "strip", "tactile"],
  "grip-edge-vertical": ["drag", "grab", "handle", "strip", "tactile"],
  "grip-mini": ["drag", "grab", "handle", "strip", "tactile"],
  group: ["cluster", "collection", "surround", "team", "together"],
  "h-align-center": ["arrange", "horizontal", "middle", "objects", "side"],
  "h-align-left": ["arrange", "flush", "horizontal", "objects", "side"],
  "h-align-right": ["arrange", "flush", "horizontal", "objects", "side"],
  "hand-closed": ["choose", "grab", "hold", "select"],
  "hand-open": ["choose", "pan", "select", "wave"],
  "hand-pinch": ["gesture", "motion", "pull", "zoom"],
  "hand-point": [
    "choose",
    "direct",
    "index finger",
    "point",
    "select",
    "tap",
    "touch",
  ],
  hdmi: ["cable", "connection", "display", "head", "port"],
  head: [
    "anatomy",
    "body",
    "brain",
    "face",
    "hear",
    "mind",
    "noggin",
    "see",
    "think",
  ],
  header: ["headline", "hook", "main", "sub", "summary", "title"],
  headset: [
    "audio",
    "av",
    "chat",
    "headphones",
    "microphone",
    "sound",
    "speaker",
    "voice",
  ],
  health: [
    "aid",
    "cross",
    "doctor",
    "emergency",
    "hospital",
    "medical",
    "nurse",
  ],
  heart: ["favorite", "like", "rate", "rating", "romance", "save"],
  "heart-off": ["favorite", "like", "rate", "rating", "romance", "save"],
  helicopter: [
    "aircraft",
    "aviation",
    "flight",
    "fly",
    "hover",
    "rotors",
    "vehicle",
  ],
  "help-circle": ["answers", "faq", "mark", "query", "question", "support"],
  "high-kick": ["casual", "fighting", "game", "genre", "martial arts"],
  "high-quality": ["image", "iq", "performance", "video"],
  highlighter: [
    "color",
    "education",
    "mark",
    "pen",
    "showcase",
    "stationary",
    "study",
  ],
  hill: ["rise", "rolling"],
  history: [
    "archive",
    "backup",
    "events",
    "happened",
    "old",
    "past",
    "previous",
    "recall",
    "sequence",
    "time",
  ],
  hit: ["boxing", "fight", "game", "genre", "martial arts", "match", "punch"],
  home: ["building", "house", "main", "start"],
  "home-off": ["building", "house", "main", "no start"],
  "hot-air-balloon": [
    "air",
    "classic",
    "explore",
    "rise",
    "travel",
    "whimsical",
  ],
  hourglass: ["busy", "delay", "pause", "process", "wait"],
  "hourglass-end": ["busy", "delay", "pause", "process", "wait"],
  "hourglass-mid": ["busy", "delay", "pause", "process", "wait"],
  "hourglass-start": ["busy", "delay", "pause", "process", "wait"],
  hud: ["components", "heads up display", "overlay", "widgets"],
  hydrant: [
    "department",
    "emergency",
    "protection",
    "safety",
    "street",
    "supply",
    "water",
  ],
  identification: [
    "badge",
    "card",
    "identity",
    "name",
    "photo",
    "security",
    "tag",
  ],
  image: [
    "drawing",
    "graphic",
    "media",
    "painting",
    "photography",
    "picture",
    "print",
  ],
  ime: ["input", "language", "method"],
  import: ["convert", "embed", "insert", "process", "translate"],
  "import-image": [
    "convert",
    "embed",
    "insert",
    "picture",
    "process",
    "translate",
    "visual",
  ],
  inbox: ["email", "incoming", "letter", "receive", "to do"],
  infinity: ["loop", "math", "neverending", "symbol", "unlimited"],
  "info-circle": [
    "attention",
    "contextual",
    "fyi",
    "help",
    "information",
    "news",
    "tip",
  ],
  instance: [
    "clone",
    "copy",
    "image",
    "likeness",
    "reflection",
    "same",
    "virtual",
  ],
  isp: ["internet", "network", "online", "wan", "web", "www"],
  "isp-off": ["internet", "no network", "online", "wan", "web", "www"],
  italic: ["document", "emphasis", "oblique", "slant", "text"],
  iterate: ["cycles", "iterations", "passes", "repeats", "steps"],
  "joystick-classic": [
    "arcade",
    "controller",
    "gaming",
    "input",
    "peripheral",
    "retro",
  ],
  key: ["access", "authentication", "entry", "lock", "open", "password"],
  keyboard: ["data entry", "input", "keys", "peripheral", "type"],
  keyframe: ["adjust", "change", "node", "point", "stop", "tween"],
  knife: [
    "cut",
    "cutlery",
    "dining",
    "food",
    "meal",
    "slice",
    "tableware",
    "utensil",
  ],
  lamp: ["decor", "electricity", "fixture", "light", "shade"],
  laptop: ["computer", "notebook", "portable"],
  laser: ["beam", "bright", "flash. els"],
  lasso: ["copy", "cut", "design", "edit", "graphics", "selection", "surround"],
  layers: ["order", "overlay", "pile", "stack"],
  "layers-off": ["no order", "overlay", "pile", "stack"],
  "layout-columns": ["grid", "template", "vertical"],
  "layout-detail": ["information", "list", "navigation", "panels", "sections"],
  "layout-grid": ["blocks", "modules", "template"],
  "layout-list": ["grid", "template"],
  "layout-rows": ["grid", "horizontal", "template"],
  library: ["books", "collection", "objects", "shelf", "stack", "volumes"],
  "library-games": [],
  license: [
    "drivers",
    "identification",
    "identity",
    "legal",
    "name",
    "photo",
    "proof",
  ],
  lifebuoy: ["float", "help", "ring", "safety"],
  "light-rect": ["illumination", "square"],
  "light-rotate": ["bulb", "spin"],
  lightbulb: ["bright", "idea", "thought"],
  lighthouse: [
    "LED",
    "beacon",
    "bright",
    "guide",
    "navigation",
    "safety",
    "tower",
    "unit identifier",
  ],
  lightning: ["electricity", "event", "instance", "juice", "power", "surprise"],
  "line-segment": ["line", "nodes", "piece", "straight"],
  link: ["chain", "connection", "hyperlink", "jump", "url", "web"],
  "link-break": [
    "chain",
    "connection",
    "hyperlink",
    "jump",
    "remove",
    "url",
    "web",
  ],
  "list-bullet": ["collection", "group", "sequence", "unordered"],
  "list-checkmark": [
    "collection",
    "group",
    "notes",
    "reminder",
    "schedule",
    "sequence",
    "summary",
    "tasks",
    "to do",
    "unordered",
    "work",
  ],
  "list-number": ["collection", "group", "ordered", "sequence", "steps"],
  location: ["geography", "marker", "pin", "place", "position"],
  "location-off": ["geography", "marker", "pin", "place", "position"],
  "lock-closed": [
    "access",
    "key",
    "keyhole",
    "locked",
    "padlock",
    "password",
    "privacy",
    "private",
    "protection",
    "safe",
    "secure",
    "security",
  ],
  "lock-open": [
    "access",
    "key",
    "keyhole",
    "padlock",
    "password",
    "privacy",
    "private",
    "protection",
    "safe",
    "secure",
    "security",
    "unlocked",
  ],
  loop: ["again", "audio", "music", "repeat"],
  "loop-off": ["audio", "disabled", "music", "no repeat", "stop repeating"],
  mac: ["apple", "display", "imac", "macintosh", "monitor", "screen"],
  "mac-off": ["apple", "display", "imac", "macintosh", "monitor", "screen"],
  magnet: ["attraction", "connection", "electromagnetism", "sticky"],
  "magnifying-glass": [
    "enlarge",
    "find",
    "inspect",
    "magnifier",
    "search",
    "shrink",
    "view",
    "zoom",
  ],
  "magnifying-glass-minus": [
    "magnifier",
    "reduce",
    "shrink",
    "view",
    "zoom out",
  ],
  "magnifying-glass-plus": ["enlarge", "magnifier", "view", "zoom in"],
  man: ["male", "men", "restrooms"],
  "man-woman": ["female", "male", "men", "restrooms", "women"],
  map: ["directions", "fold", "geography", "location", "paper"],
  "map-off": ["directions", "fold", "geography", "location", "paper"],
  mapping: ["bucketing", "clustering", "collecting", "grouping", "sorting"],
  markdown: ["documentation", "format", "shorthand", "syntax"],
  martini: ["alcohol", "bar", "cocktail", "drink", "mixology"],
  "mask-inside": ["affect", "area", "interior", "region", "select"],
  "mask-outside": ["affect", "area", "exterior", "region", "select"],
  material: ["lighting", "reflection", "render", "surface"],
  math: [
    "add",
    "divide",
    "multiply",
    "process",
    "solution",
    "solve",
    "subtract",
  ],
  meal: ["breakfast", "covered", "dinner", "food", "hand", "lunch", "served"],
  "media-optical": ["cd", "disc", "dvd", "installer"],
  medicine: [
    "dosage",
    "dose",
    "health",
    "medication",
    "medicine",
    "pharmacy",
    "prescription",
  ],
  megaphone: [
    "amplify",
    "announce",
    "bullhorn",
    "loudspeaker",
    "public address",
    "volume",
  ],
  menu: ["burger", "drawer", "hamburger", "list", "nav", "navigation", "stack"],
  microphone: ["audio", "capsule", "receive", "record", "stand", "voice"],
  "microphone-off": [
    "audio",
    "capsule",
    "disabled",
    "no voice",
    "receive",
    "stand",
  ],
  microscope: ["inspect", "lab", "magnify", "science", "zoom"],
  "mini-displayport": ["cable", "connection", "display", "head", "port"],
  "mirror-horizontal": ["reflect", "reverse"],
  "mirror-vertical": ["reflect", "reverse"],
  "mode-component": [
    "individual",
    "one",
    "single",
    "singular",
    "solo",
    "unique",
  ],
  money: [
    "bill",
    "coin",
    "currency",
    "generic",
    "stack",
    "tender",
    "universal",
    "wallet",
  ],
  "money-coin": [
    "change",
    "currency",
    "generic",
    "tender",
    "universal",
    "wallet",
  ],
  "money-paper": [
    "bill",
    "currency",
    "dollar",
    "frank",
    "generic",
    "note",
    "pound",
    "tender",
    "universal",
    "wallet",
  ],
  moon: ["crescent", "dark", "eclipse", "evening", "night", "space"],
  "moon-off": ["crescent", "dark", "eclipse", "evening", "night", "space"],
  "more-horiz": [
    "configuration",
    "dots",
    "ellipses",
    "ellipsis",
    "menu",
    "options",
  ],
  "more-vert": [
    "configuration",
    "dots",
    "ellipses",
    "ellipsis",
    "menu",
    "options",
  ],
  mosaic: ["cave", "combined displays", "fabric", "resolution", "wall"],
  mountain: ["high point", "peak", "range", "rocky"],
  "mouse-2b": ["buttons", "cursor", "input", "peripheral", "track"],
  "mouse-2b-right-click": ["action", "buttons", "indicator"],
  "mouse-3-b": ["buttons", "cursor", "input", "peripheral", "track"],
  "mouse-scrollwheel": ["buttons", "cursor", "input", "peripheral", "track"],
  "mouse-scrollwheel-active": ["action", "buttons", "indicator", "wheel"],
  move: ["adjust", "arrows", "change", "cross", "relocate"],
  "move-global": ["adjust", "arrows", "change", "cross", "object", "relocate"],
  mud: ["dirt", "water"],
  mug: [
    "beverage",
    "coffee",
    "cup",
    "drink",
    "hot",
    "hot chocolate",
    "steam",
    "tea",
    "warm",
  ],
  "mug-beer": ["alcohol", "ale", "bar", "drink", "pub", "stein"],
  multidrive: [
    "array",
    "discs",
    "hard drives",
    "hdd",
    "raid",
    "save",
    "storage",
    "store",
    "stripe",
  ],
  network: ["connections", "diagram", "hub", "lines", "nodes", "web"],
  "network-connection": ["ethernet", "lan", "local area network"],
  "network-pcs": [
    "cluster",
    "computers",
    "connection",
    "group",
    "lan",
    "local area",
  ],
  "network-signal": ["activity", "node", "origin", "pulse"],
  "network-signal-off": ["activity", "no origin", "node", "pulse"],
  "neural-network": [
    "ai",
    "artificial intelligence",
    "deep",
    "dl",
    "learning",
    "machine",
    "ml",
  ],
  news: [
    "articles",
    "headlines",
    "information",
    "pages",
    "periodical",
    "press",
    "tabloid",
    "update",
  ],
  next: ["after", "end", "jump", "skip"],
  "not-equal": ["different", "equation", "math", "not same"],
  notes: ["bar", "melody", "music", "notation"],
  numbers: ["count", "digits", "numeric", "values"],
  "nvidia-shield": ["console", "set top box", "stb"],
  "nvidia-shield-stand": ["console", "set top box", "stb", "vertical"],
  "open-external": ["launch", "new", "outside", "share"],
  os: ["base", "computer", "os", "software"],
  outbox: ["email", "exiting", "letter", "outgoing", "sending"],
  "outlet-a": ["plug", "power", "receptacle", "socket", "wiring"],
  "outlet-b": ["plug", "power", "receptacle", "socket", "wiring"],
  "outlet-c": ["plug", "power", "receptacle", "socket", "wiring"],
  "outlet-e": ["plug", "power", "receptacle", "socket", "wiring"],
  "outlet-g": ["plug", "power", "receptacle", "socket", "wiring"],
  "outlet-h": ["plug", "power", "receptacle", "socket", "wiring"],
  "outlet-i": ["plug", "power", "receptacle", "socket", "wiring"],
  "outlet-j": ["plug", "power", "receptacle", "socket", "wiring"],
  "outlet-k": ["plug", "power", "receptacle", "socket", "wiring"],
  "outlet-l": ["plug", "power", "receptacle", "socket", "wiring"],
  outpainting: ["canvas", "create", "extend", "grow", "stretch"],
  package: ["address", "box", "label", "order", "send", "shipment"],
  palette: ["collection", "colors", "picker"],
  paperclip: ["addition", "attachment", "extra", "file"],
  paperplane: ["email", "flying", "folded", "message", "send"],
  paragraph: [
    "characters",
    "document",
    "hidden",
    "new",
    "processor",
    "special",
    "start",
    "text",
  ],
  park: [
    "location",
    "nature",
    "outdoors",
    "outside",
    "picnic",
    "playground",
    "public",
    "recreation",
  ],
  pause: ["control", "playback", "stop", "transport"],
  pawn: ["casual", "chess", "game", "genre", "marker", "player", "strategy"],
  pawprint: [
    "animal",
    "foot",
    "nature",
    "path",
    "pet",
    "step",
    "track",
    "walk",
    "wildlife",
  ],
  "payment-card": [
    "buy",
    "commerce",
    "credit",
    "debit",
    "finance",
    "money",
    "purchase",
    "shop",
    "swipe",
  ],
  pen: ["ballpoint", "edit", "ink", "permanent", "write"],
  pencil: [
    "change",
    "create",
    "draw",
    "edit",
    "modify",
    "pencil",
    "stylus",
    "write",
  ],
  "performance-high": [
    "benchmark",
    "capacity",
    "dashboard",
    "gauge",
    "high",
    "measure",
    "threshold",
  ],
  "performance-low": [
    "benchmark",
    "capacity",
    "dashboard",
    "gauge",
    "low",
    "measure",
    "threshold",
  ],
  "performance-medium": [
    "benchmark",
    "capacity",
    "dashboard",
    "gauge",
    "measure",
    "medium",
    "threshold",
  ],
  "phone-laptop": [
    "android",
    "combo",
    "computer",
    "gadget",
    "handset",
    "iphone",
    "notebook",
    "pair",
    "portable",
  ],
  "physical-exit": ["emergency", "escape", "flee", "leave"],
  "picture-in-picture": ["mini", "preview", "small", "video", "window"],
  "pill-bar-stack": ["collection", "grouping", "properties", "tags"],
  pin: ["keep", "present", "remember", "set", "thumbtack"],
  "pin-off": ["keep", "no thumbtack", "present", "remember", "set"],
  pizza: ["cuisine", "food", "italian", "pie", "slice", "toppings"],
  placesetting: [
    "cup",
    "etiquette",
    "fine dining",
    "food",
    "meal",
    "plate",
    "tableware",
    "utensils",
  ],
  platformer: ["casual", "climbing", "game", "genre", "jumping", "running"],
  play: ["begin", "control", "go", "move", "playback", "start", "transport"],
  "plug-receptacle": ["connect", "couple", "electricity", "power", "socket"],
  "plug-usb": ["cable", "connect"],
  plugin: ["electricity", "power", "prongs"],
  podium: ["lectern", "present", "speaking", "stage"],
  power: ["circuit", "device", "electronics", "flow", "hardware", "state"],
  "power-supply-unit": ["bolt", "electricity", "source", "wiring"],
  "prayer-room": ["chapel", "meditation", "quiet", "religion"],
  previous: ["before", "beginning", "jump", "prior", "skip"],
  profile: ["account", "avatar", "person", "photo", "user"],
  "profile-group": ["accounts", "avatars", "people", "photos", "users"],
  "profile-off": ["account", "avatar", "no user", "person", "photo"],
  projector: ["display", "present", "showcase", "stand"],
  pulse: ["audio", "health", "heartbeat", "sound", "statistic", "wavelength"],
  puzzle: ["component", "fit", "mystery", "piece"],
  qrcode: ["dots", "encode", "link", "mobile", "pattern", "quick redirect"],
  radar: ["ping", "scan", "sensor", "sonar", "waves"],
  radioactive: ["energy", "nuclear", "warning"],
  ram: ["chip", "micro", "random access memory", "storage"],
  "ranking-xp": ["badge", "experience", "level", "points", "skill"],
  record: ["capture", "control", "grab", "media", "playback", "transport"],
  "rectangle-group": ["areas", "arrange", "blocks", "gather", "sort"],
  redo: ["again", "arrow", "forward", "next", "restore"],
  reference: ["image", "likeness", "pointer", "proxy", "same"],
  refresh: ["check", "replenish", "restore", "try again", "update"],
  remote: ["control", "distance", "gadget", "shield", "television", "tv"],
  rename: ["edit", "file", "manage"],
  render: ["final", "hybrid", "image", "landscape"],
  replay: ["again", "feature", "movies", "shadowplay", "videos"],
  "replay-off": ["again", "movies", "no feature", "shadowplay", "videos"],
  reply: ["react", "response", "return", "send back"],
  reset: ["boot", "cycle", "replay", "start over", "try again"],
  retry: ["again", "attempt"],
  return: ["carriage", "enter", "new line"],
  "reverse-10": ["backward", "jump", "rewind", "skip"],
  river: ["channel", "flow", "water"],
  robot: ["android", "automation", "machine"],
  "robot-arm": ["articulation", "automation", "dexterity", "simulation"],
  "robot-delivery": [
    "automation",
    "courier",
    "local",
    "logistics",
    "machine",
    "transport",
    "travel",
  ],
  "robot-torso": ["android", "automation", "machine", "upper body", "waist up"],
  "robot-wheels": ["android", "automation", "machine", "rolling", "tread"],
  rock: ["boulder", "ground"],
  rocket: [
    "explore",
    "launch",
    "science",
    "send",
    "shuttle",
    "space",
    "start",
    "travel",
  ],
  rotate: ["arrows", "circle", "pivot", "roll", "spin", "swivel", "twirl"],
  "rotate-3d": [
    "arrows",
    "circle",
    "dimensions",
    "pivot",
    "roll",
    "spin",
    "swivel",
    "twirl",
  ],
  "rotate-90-clockwise": ["rectangular", "right", "spin", "square", "turn"],
  "rotate-90-counter": ["left", "rectangular", "spin", "square", "turn"],
  "rotate-global": ["object", "spin"],
  route: ["directions", "journey", "map", "navigation", "path", "travel"],
  ruler: ["distance", "measurement", "size", "straightedge"],
  running: ["action", "activity", "exercise", "figure", "movement", "person"],
  sailboat: [
    "float",
    "lake",
    "maritime",
    "ocean",
    "ship",
    "toy",
    "travel",
    "vehicle",
    "water",
    "wind powered",
  ],
  sand: ["cactus", "desert", "dry", "dunes"],
  "saw-wave": ["audio", "electronics", "music", "synthesizer", "waveform"],
  scale: ["adjust", "bigger", "expand", "reduce", "resize", "shrink"],
  "scale-balance": ["compare", "even", "measures", "weights"],
  "scale-down": ["collapse", "reduce", "resize", "shrink"],
  "scale-relative": ["aspect ratio", "enlarge", "maintain", "reduce", "shrink"],
  "scale-relative-off": [
    "aspect ratio",
    "maintain",
    "no enlarge",
    "reduce",
    "shrink",
  ],
  "scale-reset": ["original", "resize", "start"],
  "scale-up": ["expand", "grow", "resize", "stretch"],
  school: [
    "building",
    "education",
    "learning",
    "location",
    "place",
    "students",
    "teachers",
  ],
  scissors: ["break", "copy", "cut", "slice", "split"],
  "scm-branch": [
    "change",
    "code",
    "control",
    "git",
    "management",
    "new",
    "source",
    "test",
    "version",
  ],
  "scm-compare": [
    "check",
    "code",
    "control",
    "diff",
    "git",
    "management",
    "source",
    "text",
    "version",
  ],
  "scm-fork": [
    "clone",
    "code",
    "control",
    "copy",
    "git",
    "management",
    "new",
    "source",
    "version",
  ],
  "scm-merge": [
    "checkin",
    "code",
    "control",
    "git",
    "management",
    "source",
    "sync",
    "update",
    "version",
  ],
  "scm-pull": [
    "code",
    "control",
    "git",
    "management",
    "refresh",
    "source",
    "sync",
    "version",
  ],
  "scm-pull-close": [
    "cancel",
    "close",
    "code",
    "control",
    "delete",
    "git",
    "management",
    "remove",
    "source",
    "version",
  ],
  "scm-pull-draft": [
    "code",
    "control",
    "git",
    "management",
    "source",
    "temporary",
    "version",
    "working",
  ],
  "sd-card": ["camera", "data", "memory", "save", "storage", "store"],
  sea: ["ocean", "open water", "waves"],
  section: ["choose", "mark", "pick", "portion"],
  "section-bottom": ["choose", "lower", "mark", "pick", "portion", "under"],
  "section-top": ["choose", "mark", "over", "pick", "portion", "upper"],
  secure: ["assured", "checked", "protected", "safe", "trusted", "validated"],
  seed: ["acorn", "grow", "plant", "randomization"],
  segmap: ["draft", "rough", "segmentation"],
  segment: [
    "bit",
    "divide",
    "object",
    "part",
    "piece",
    "portion",
    "separate",
    "split",
  ],
  "select-brush": ["choose", "mark", "paint", "pick", "stroke"],
  "select-ellipse": [
    "area",
    "border",
    "boundary",
    "circle",
    "mask",
    "portion",
    "region",
    "round",
    "segment",
  ],
  "select-polygon": [
    "area",
    "border",
    "boundary",
    "custom",
    "irregular",
    "mask",
    "portion",
    "region",
    "segment",
  ],
  "select-rectangle": [
    "area",
    "border",
    "boundary",
    "corner",
    "mask",
    "portion",
    "region",
    "segment",
    "square",
  ],
  "send-image": [
    "convert",
    "embed",
    "media",
    "picture",
    "process",
    "send",
    "share",
    "transfer",
    "translate",
    "visual",
  ],
  sensor: ["dish", "pickup", "receiver", "receptor", "signals"],
  "service-account": ["automatic", "background", "built-in", "utility"],
  shader: ["algorithm", "computed", "lighting", "look", "materials", "render"],
  "shader-ball": [
    "demo",
    "example",
    "lighting",
    "materials",
    "object",
    "showcase",
    "textures",
  ],
  "shape-circle": ["basic", "dot", "ring", "simple"],
  "shape-circle-off": ["basic", "dot", "no simple", "ring"],
  "shape-hexagon": ["6", "basic", "bee", "honeycomb", "simple", "six", "tile"],
  "shape-octagon": ["8", "alert", "basic", "eight", "sign", "simple", "stop"],
  "shape-square": ["basic", "box", "simple"],
  "shape-square-off": [],
  "shape-triangle": ["alert", "basic", "danger", "simple", "warning"],
  shapes: [
    "basic",
    "collection",
    "containers",
    "objects",
    "primitives",
    "simple",
  ],
  share: [
    "colleagues",
    "community",
    "coworkers",
    "distribute",
    "friends",
    "give",
    "message",
    "send",
    "social",
  ],
  shield: [
    "block",
    "elevation",
    "guard",
    "malware",
    "protection",
    "safety",
    "security",
    "virus",
  ],
  "shield-off": [
    "block",
    "elevation",
    "guard",
    "malware",
    "protection",
    "safety",
    "security",
    "virus",
  ],
  ship: [
    "cruise",
    "luxury",
    "maritime",
    "massive",
    "ocean liner",
    "titanic",
    "travel",
    "vacation",
    "vehicle",
    "vessel",
    "voyage",
  ],
  "ship-wheel": [
    "boat",
    "directions",
    "discover",
    "explore",
    "navigate",
    "steer",
  ],
  "shopping-bag": ["bundle", "buy", "choose", "commerce", "purchase", "shop"],
  "shopping-basket": [
    "bag",
    "bundle",
    "buy",
    "checkout",
    "commerce",
    "items",
    "purchase",
    "store",
  ],
  "shopping-cart": [
    "bundle",
    "buy",
    "checkout",
    "commerce",
    "items",
    "purchase",
    "store",
  ],
  "shopping-cart-open": [
    "bundle",
    "buy",
    "checkout",
    "commerce",
    "contents",
    "filled",
    "items",
    "purchase",
    "store",
  ],
  shuffle: ["disorder", "mix", "playlist", "random", "sequence"],
  signature: ["autograph", "sign"],
  signpost: ["direction", "goal", "marker", "pointer", "waypoint"],
  "sin-wave": ["audio", "electronics", "music", "synthesizer", "waveform"],
  skeleton: ["bones", "joints", "limbs", "parts", "pieces", "segments"],
  skip: ["avoid", "ignore", "over"],
  skull: ["danger", "dead", "death", "skeleton"],
  sky: ["air", "birds", "horizon", "ocean", "sunset"],
  sliders: [
    "adjust",
    "configuration",
    "continuous",
    "controls",
    "options",
    "refine",
    "settings",
  ],
  smartphone: ["android", "gadget", "handset", "iphone"],
  "smartphone-off": ["android", "gadget", "handset", "iphone"],
  snow: ["cold", "crystal", "flake", "hexagonal", "temperature", "water"],
  soccer: ["ball", "casual", "game", "genre", "sports"],
  sort: ["hierarchy", "order", "sequence"],
  "sort-ascending": ["direction", "hierarchy", "order", "sequence"],
  "sort-descending": ["direction", "hierarchy", "order", "sequence"],
  soundwaves: ["amplitude", "audio", "levels"],
  sparkle: ["magic", "poof", "shiny", "stars", "twinkle", "whoosh"],
  speaker: ["audio", "music", "sound", "volume"],
  "speaker-high": ["audio", "loud", "max", "music", "sound", "volume"],
  "speaker-low": ["audio", "min", "music", "quiet", "sound", "volume"],
  "speaker-medium": ["audio", "medium", "music", "normal", "sound", "volume"],
  "speaker-mute": ["audio", "music", "quiet", "sound", "volume"],
  "speaker-off": ["audio", "disabled", "music", "sound", "volume"],
  split: ["divide", "separate", "split"],
  "split-file": ["divide", "separate"],
  spoon: [
    "cutlery",
    "dining",
    "food",
    "liquid",
    "meal",
    "scoop",
    "soup",
    "tableware",
    "utensil",
  ],
  "square-wave": ["audio", "electronics", "music", "synthesizer", "waveform"],
  "stack-horizontal": ["flow", "order", "overlay", "pile", "stack"],
  stair: ["emergency", "floors", "staircase", "stairwell"],
  star: ["award", "favorite", "level", "rate", "rating"],
  "steering-wheel": [
    "automotive",
    "control",
    "racing",
    "spin",
    "steer",
    "turn",
    "vehicle",
    "wheels",
  ],
  "step-forward": ["frame", "jump", "next", "skip", "slow"],
  "step-reverse": ["frame", "jump", "previous", "prior", "skip", "slow"],
  sticker: ["cover", "overlay", "superimpose", "tag"],
  "sticker-image": [
    "copy",
    "information",
    "on top",
    "overlay",
    "type",
    "write",
  ],
  "sticker-shape": [
    "copy",
    "information",
    "on top",
    "overlay",
    "type",
    "write",
  ],
  "sticker-text": ["copy", "information", "on top", "overlay", "type", "write"],
  "sticker-zoom": ["copy", "information", "on top", "overlay", "type", "write"],
  stone: ["face", "hewn", "rock"],
  stop: ["control", "end", "playback", "transport"],
  straw: ["grassland", "stalks", "tall"],
  strikethrough: ["document", "recant", "redact", "remove", "text"],
  "stroke-width": ["edge", "line", "thickness"],
  style: ["customize", "freestyle", "look", "visuals"],
  subtract: ["delete", "minus", "remove"],
  "subtract-circle": ["delete", "minus", "remove"],
  "suit-club": ["cards", "game", "playing", "suit"],
  "suit-diamond": ["cards", "game", "playing", "suit"],
  "suit-spade": ["cards", "game", "playing", "suit"],
  suitcase: ["baggage", "clothes", "personal", "travel"],
  "sun-high": ["astronomy", "bright", "intensity", "light", "space"],
  "sun-low": ["astronomy", "dim", "intensity", "light", "space"],
  "sun-off-high": ["astronomy", "bright", "intensity", "light", "space"],
  swatches: ["cards", "categories", "fan", "sets", "stack", "styles", "types"],
  sword: ["casual", "fantasy", "game", "genre", "role playing", "rpg"],
  sync: [
    "activity",
    "arrows",
    "connection",
    "feedback",
    "recurring",
    "schedule",
  ],
  "sync-off": [
    "activity",
    "arrows",
    "feedback",
    "no connection",
    "recurring",
    "schedule",
  ],
  "sync-warning": ["blocked", "broken", "error", "issue", "stopped"],
  tablet: ["android", "gadget", "ipad", "kindle", "slate"],
  "tablet-off": ["android", "gadget", "ipad", "kindle", "slate"],
  tag: ["categorize", "flag", "label", "mark", "price"],
  "tag-label": ["categorize", "flag", "label", "mark", "price"],
  teapot: ["beverage", "boil", "cup", "example", "hot"],
  telephone: ["answer", "call", "communications", "handset", "pickup"],
  "telephone-off": ["answer", "call", "communications", "handset", "pickup"],
  teleport: ["translation", "transport", "travel", "wormhole"],
  telescope: [
    "astronomy",
    "explore",
    "optics",
    "planets",
    "science",
    "space",
    "stars",
    "zoom",
  ],
  television: [
    "broadcast",
    "display",
    "entertainment",
    "media",
    "screen",
    "shows",
    "tv",
  ],
  "television-retro": [
    "broadcast",
    "classic",
    "display",
    "entertainment",
    "media",
    "screen",
    "shows",
    "tv",
  ],
  text: ["dictate", "document", "letters", "type", "words", "write"],
  "text-align-center": ["balanced", "format", "middle", "ragged", "text"],
  "text-align-full": ["flush", "format", "full", "justified", "text"],
  "text-align-left": ["flush", "format", "justified", "text"],
  "text-align-right": ["flush", "format", "justified", "text"],
  "text-framed": ["background", "boundary", "box", "color", "region"],
  texture: ["material", "render", "roughness", "surface"],
  thermometer: ["gauge", "measure", "temperature"],
  "thumb-down": [
    "disapprove",
    "dislike",
    "negative",
    "opinion",
    "rate",
    "rating",
    "reject",
  ],
  "thumb-up": ["approve", "like", "opinion", "positive", "rate", "rating"],
  ticket: ["event", "pass", "redeem", "tix", "validation"],
  timer: ["clock", "measure", "period", "race", "stop watch", "time"],
  toolbox: [
    "adjust",
    "configuration",
    "customize",
    "fix",
    "repair",
    "utilities",
  ],
  "traffic-cone": [
    "barrier",
    "construction",
    "guidance",
    "marker",
    "safety",
    "warning",
  ],
  "transfer-horizontal": [
    "displace",
    "exchange",
    "horizontal",
    "migrate",
    "move",
    "relocate",
    "shift",
    "sideways",
    "switch",
  ],
  "transfer-vertical": [
    "displace",
    "exchange",
    "migrate",
    "move",
    "relocate",
    "shift",
    "switch",
    "vertical",
  ],
  transform: ["blocks", "change", "cube", "process"],
  transparency: [
    "onion",
    "opacity",
    "see through",
    "skin",
    "translucency",
    "vellum",
  ],
  trash: [
    "bin",
    "can",
    "delete",
    "garbage",
    "recycle",
    "remove",
    "rubbish",
    "waste",
  ],
  "trash-delete": ["empty", "files", "garbage can", "permanent"],
  tree: ["branches", "forest", "leaves", "trunk", "woods"],
  trees: ["forest", "grove", "stand", "woods"],
  "triangle-wave": ["audio", "electronics", "music", "synthesizer", "waveform"],
  trident: ["fishing", "fork", "mythology", "poseidon", "spear", "weapon"],
  typography: [
    "appearance",
    "font",
    "format",
    "legibility",
    "letters",
    "readability",
    "style",
    "words",
  ],
  umbrella: ["dry", "protection", "rain"],
  underline: ["document", "emphasis", "hyperlink", "rule", "text"],
  undo: ["arrow", "back", "backwards", "previous", "reverse", "revert"],
  upload: ["push", "put", "send", "up arrow"],
  usb: ["format", "peripheral", "standard", "type", "wired"],
  "v-align-bottom": ["arrange", "flush", "objects", "side", "vertical"],
  "v-align-center": ["arrange", "middle", "objects", "side", "vertical"],
  "v-align-top": ["arrange", "flush", "objects", "side", "vertical"],
  vga: ["cable", "connection", "display", "head", "port"],
  videocam: ["action", "camera", "live", "movie", "playback", "record"],
  "videocam-off": [
    "action",
    "disabled",
    "live",
    "movie",
    "no camera",
    "playback",
    "record",
  ],
  vr: ["goggles", "peripheral", "track", "virtual reality"],
  wand: ["automatic", "fix", "improve", "instant", "magic", "wizard"],
  warning: [
    "alert",
    "attention",
    "caution",
    "danger",
    "error",
    "feedback",
    "issue",
    "triangle",
  ],
  watch: ["clock", "time", "wearable", "wrist"],
  "watch-party": [
    "event",
    "group",
    "keynote",
    "presentation",
    "session",
    "streaming",
    "video",
    "view",
  ],
  water: ["lake", "liquid", "smooth", "still", "wet"],
  "weather-cloud": ["forecast", "gray", "overcast"],
  "weather-fog": ["cloudy", "forecast", "gray", "hazy", "low visibility"],
  "weather-lightning": ["bolt", "electricity", "forecast", "strike"],
  "weather-partial-cloud-day": ["forecast", "mixed", "partial", "sun"],
  "weather-partial-cloud-night": ["forecast", "mixed", "moon", "partial"],
  "weather-rain": ["downpour", "drizzle", "forecast", "rainy", "wet"],
  "weather-snow": ["Forecast", "blizzard", "cold", "icy"],
  "weather-wind": ["blast", "blustery", "gale", "gust"],
  webcam: ["camera", "meetings", "mount", "video chat"],
  "webcam-off": ["camera", "meetings", "mount", "video chat"],
  "webcam-settings": [
    "adjust",
    "camera",
    "config",
    "meetings",
    "mount",
    "settings",
    "video chat",
  ],
  weight: ["big", "force", "heavy", "mass", "measurement"],
  "weight-bar": ["barbell", "exercise", "heavy", "lift", "work out"],
  wheel: [
    "circular",
    "hub",
    "machine",
    "rotation",
    "spin",
    "spokes",
    "turn",
    "vehicle",
  ],
  wheelchair: [
    "accessibility",
    "ada",
    "disabled",
    "handicap",
    "parking",
    "ramp",
    "space",
  ],
  whispermode: ["fan", "feature", "noise", "quiet", "silent", "volume"],
  wifi: ["hotspot", "internet", "reception", "signal", "waves", "wireless"],
  "wifi-off": [
    "disabled",
    "hotspot",
    "internet",
    "reception",
    "signal",
    "waves",
    "wireless",
  ],
  window: ["application", "browser", "frame"],
  "window-code": ["developer", "ide", "integrated development environment"],
  "window-grid": ["all up", "apps", "divided", "quadrants", "tiled"],
  "window-stack": ["applications", "apps", "collection", "group", "overlay"],
  "window-terminal": ["cli", "command line interface", "console", "terminal"],
  "wine-glass": ["alcohol", "bar", "cup", "drink", "wine"],
  "wireless-modem": [
    "internet",
    "lan",
    "network",
    "router",
    "signal",
    "wap",
    "wifi",
  ],
  "wireless-modem-off": [
    "internet",
    "lan",
    "network",
    "router",
    "signal",
    "wap",
    "wifi",
  ],
  woman: ["female", "restrooms", "women"],
  workspace: [
    "applications",
    "apps",
    "desktop",
    "files",
    "job",
    "structure",
    "workflow",
  ],
  "workspace-group": [
    "applications",
    "apps",
    "collection",
    "desktop",
    "files",
    "job",
    "structure",
    "workflow",
  ],
  workstation: ["computer", "desktop", "pc", "tower"],
  "workstation-off": ["computer", "desktop", "pc", "tower"],
  "workstation-system": [
    "computer",
    "desktop",
    "display",
    "monitor",
    "pc",
    "tower",
  ],
  "workstation-system-off": [
    "computer",
    "desktop",
    "display",
    "monitor",
    "pc",
    "tower",
  ],
  world: ["earth", "global", "globe", "internet", "planet", "wan", "www"],
  "world-off": ["earth", "global", "globe", "internet", "planet", "wan", "www"],
  wrench: ["adjust", "build", "customize", "fix", "repair", "tool"],
  yoke: [
    "aircraft",
    "aviation",
    "control",
    "flight",
    "flying",
    "pilot",
    "simulator",
    "steer",
  ],
};
